-- Additional Japanese search candidates from NANDO shoman_class.json.
-- NANDO repo: https://github.com/NanbyoData/nando (CC BY 4.0, DBCLS).
-- Only non-root pediatric classification entries, excluding vague "others".
-- 47 exact normalized name matches were NOT reinserted; 233 novel groups.
-- Beware these are disease categories, not necessarily unique atomic diseases.
alter table public.disease_catalog
 add column if not exists classification_source text,
 add column if not exists classification_source_id text,
 add column if not exists concept_kind text not null default 'named_disease';
create unique index if not exists disease_catalog_classification_source_uidx
 on public.disease_catalog(classification_source,classification_source_id)
 where classification_source_id is not null;
insert into public.disease_catalog
 (id,name_ja,name_en,source_url,classification_source,classification_source_id,
  concept_kind,medical_review_status,published)
 select x.id,x.name_ja,nullif(x.name_en,''),
  'https://github.com/NanbyoData/nando/blob/master/data/shoman_class.json',
  'NANDO:shoman_class',x.source_id,'pediatric_disease_group',
  'name-only-unreviewed',true
 from (values ('shoman-1-1','白血病','leukemia','1-1'),
('shoman-1-2','骨髄異形成症候群','Myelodysplastic syndrome','1-2'),
('shoman-1-3','リンパ腫','Lymphoma','1-3'),
('shoman-1-4','組織球症','Histiocytosis','1-4'),
('shoman-1-5','固形腫瘍（中枢神経系腫瘍を除く。）','Solid tumor (excluding solid tumour of the central nervous system)','1-5'),
('shoman-1-6','中枢神経系腫瘍','Central nervous system tumors','1-6'),
('shoman-2-1','ネフローゼ症候群','Nephrotic syndrome','2-1'),
('shoman-2-2','慢性糸球体腎炎','Chronic glomerulonephritis','2-2'),
('shoman-2-3','慢性尿細管間質性腎炎（尿路奇形が原因のものを除く。）','Chronic tubulointerstitial nephritis (excluding urinary tract malformation)','2-3'),
('shoman-2-4','慢性腎盂腎炎','Chronic pyelonephritis','2-4'),
('shoman-2-5','アミロイド腎','Amyloid nephropathy','2-5'),
('shoman-2-6','家族性若年性高尿酸血症性腎症','Familial juvenile hyperuricaemic nephropathy','2-6'),
('shoman-2-8','腎血管性高血圧','Renovascular hypertension','2-8'),
('shoman-2-9','腎静脈血栓症','Renal vein thrombosis','2-9'),
('shoman-2-10','腎動静脈瘻','Renal arteriovenous fistula','2-10'),
('shoman-2-11','尿細管性アシドーシス','Renal tubular acidosis','2-11'),
('shoman-2-12','ギッテルマン（Gitelman）症候群','Gitelman Bartter syndrome','2-12'),
('shoman-2-13','バーター（Bartter）症候群','Bartter Gitelman syndrome','2-13'),
('shoman-2-14','腎尿管結石','Nephro- and urolithiasis','2-14'),
('shoman-2-15','慢性腎不全','Chronic renal failure','2-15'),
('shoman-2-16','腎奇形','Renal malformation','2-16'),
('shoman-2-17','尿路奇形','Urinary tract malformation','2-17'),
('shoman-2-18','萎縮腎（尿路奇形が原因のものを除く。）','Atrophic kidney (excluding urinary tract malformation)','2-18'),
('shoman-2-19','ファンコーニ（Fanconi）症候群','Fanconi syndrome','2-19'),
('shoman-2-20','ロウ（Lowe）症候群','Lowe syndrome','2-20'),
('shoman-3-1','気道狭窄','Airway obstruction and stenosis','3-1'),
('shoman-3-2','気管支喘息','Bronchial asthma','3-2'),
('shoman-3-3','先天性中枢性低換気症候群','Congenital central hypoventilation syndrome','3-3'),
('shoman-3-4','間質性肺疾患','Interstitial pneumonia','3-4'),
('shoman-3-5','線毛機能不全症候群','primary ciliary dyskinesia','3-5'),
('shoman-3-7','気管支拡張症','Bronchiectasis','3-7'),
('shoman-3-8','特発性肺ヘモジデローシス','Idiopathic pulmonary hemosiderosis','3-8'),
('shoman-3-9','慢性肺疾患','Chronic lung disease','3-9'),
('shoman-3-12','先天性嚢胞性肺疾患','Congenital cystic lung disease','3-12'),
('shoman-4-1','洞不全症候群','Sick sinus syndrome','4-1'),
('shoman-4-2','モビッツ（Mobitz）2型ブロック','Mobitz type II second degree atrioventricular block','4-2'),
('shoman-4-3','完全房室ブロック','Complete atrio-ventricular block','4-3'),
('shoman-4-4','脚ブロック','Bundle branch block','4-4'),
('shoman-4-5','多源性心室期外収縮','Polymorphic ventricular premature beat','4-5'),
('shoman-4-6','上室頻拍','Supraventricular tachycardia','4-6'),
('shoman-4-7','心室頻拍','Ventricular tachycardia','4-7'),
('shoman-4-8','心房粗動','Atrial flutter','4-8'),
('shoman-4-9','心房細動','Atrial Fibrillation','4-9'),
('shoman-4-10','心室細動','Ventricular fibrillation','4-10'),
('shoman-4-11','QT延長症候群','Long QT syndrome','4-11'),
('shoman-4-13','不整脈源性右室心筋症','Arrhythmogenic right ventricular cardiomyopathy or dysplasia','4-13'),
('shoman-4-14','心筋緻密化障害','Non-compaction of the ventricle','4-14'),
('shoman-4-15','拡張型心筋症','Dilated cardiomyopathy','4-15'),
('shoman-4-17','心室瘤','Aneurysm of ventricle','4-17'),
('shoman-4-18','心内膜線維弾性症','Endocardial fibroelastosis','4-18'),
('shoman-4-19','心臓腫瘍','Cardiac tumor','4-19'),
('shoman-4-20','慢性心筋炎','Chronic myocarditis','4-20'),
('shoman-4-21','慢性心膜炎','Chronic pericarditis','4-21'),
('shoman-4-22','収縮性心膜炎','Constrictive pericarditis','4-22'),
('shoman-4-23','先天性心膜欠損症','Congenital defect of the pericardium','4-23'),
('shoman-4-24','乳児特発性僧帽弁腱索断裂','Idiopathic Rupture of Chordae Tendineae of the Mitral Valve in Infants','4-24'),
('shoman-4-25','冠動脈起始異常','Abnormal origin of coronary artery from pulmonary artery','4-25'),
('shoman-4-26','川崎病性冠動脈瘤','Coronary aneurysms complicated with kawasaki disease','4-26'),
('shoman-4-27','冠動脈狭窄症（川崎病によるものを除く。）','Stenosis or atresia of coronary artery','4-27'),
('shoman-4-28','虚血性心疾患','Ischemic heart disease','4-28'),
('shoman-4-32','肺動脈閉鎖症','Pulmonary atresia','4-32'),
('shoman-4-33','ファロー（Fallot）四徴症','Tetralogy of Fallot','4-33'),
('shoman-4-35','両大血管左室起始症','Double-outlet left ventricle','4-35'),
('shoman-4-37','先天性修正大血管転位症','Congenitally corrected transposition of the great arteries','4-37'),
('shoman-4-38','エプスタイン（Ebstein）病','Ebstein’s anomaly','4-38'),
('shoman-4-40','大動脈肺動脈窓','Aorto-pulmonary window','4-40'),
('shoman-4-41','三心房心','Cor triatriatum','4-41'),
('shoman-4-42','動脈管開存症','Patent ductus arteriosus','4-42'),
('shoman-4-43','心房中隔欠損症','Atrial septal defect','4-43'),
('shoman-4-44','完全型房室中隔欠損症','Complete atrioventricular septal defect','4-44'),
('shoman-4-45','心室中隔欠損症','Ventricular septal defect','4-45'),
('shoman-4-46','肺静脈還流異常症','Total anomalous pulmonary venous connection','4-46'),
('shoman-4-47','肺静脈狭窄症','Pulmonary venous obstruction','4-47'),
('shoman-4-48','左室右房交通症','Left ventricular-right atrial communication','4-48'),
('shoman-4-49','右室二腔症','Double-chambered right ventricle','4-49'),
('shoman-4-50','肺動脈弁下狭窄症','Subvalvular pulmonary stenosis','4-50'),
('shoman-4-51','大動脈弁下狭窄症','Subvalvular aortic stenosis','4-51'),
('shoman-4-52','肺動脈狭窄症','Supravalvular pulmonary stenosis','4-52'),
('shoman-4-53','肺動脈弁欠損','Absent pulmonary valve','4-53'),
('shoman-4-54','肺動脈上行大動脈起始症','Origin of pulmonary artery from ascending aorta','4-54'),
('shoman-4-55','一側肺動脈欠損','Unilateral absence of a pulmonary artery','4-55'),
('shoman-4-56','大動脈狭窄症','Coarctation of the aorta','4-56'),
('shoman-4-57','大動脈弓閉塞症','Aortic arch occlusive disease','4-57'),
('shoman-4-58','血管輪','Vascular ring','4-58'),
('shoman-4-59','大動脈瘤','Aortic aneurysm','4-59'),
('shoman-4-60','動静脈瘻','Arteriovenous fistulae','4-60'),
('shoman-4-62','慢性肺性心','Chronic cor pulmonale','4-62'),
('shoman-4-63','心臓弁膜症','Valvular heart disease','4-63'),
('shoman-4-64','僧帽弁弁上輪','Supramitral ring','4-64'),
('shoman-4-65','内臓錯位症候群','Hheterotaxy syndrome','4-65'),
('shoman-4-66','フォンタン（Fontan）術後症候群','Post-Fontan syndrome','4-66'),
('shoman-5-1','下垂体機能低下症','Hypopituitarism','5-1'),
('shoman-5-2','下垂体性巨人症','Pituitary gigantism','5-2'),
('shoman-5-3','先端巨大症','Acromegaly','5-3'),
('shoman-5-4','成長ホルモン分泌不全性低身長症','Growth hormone deficiency','5-4'),
('shoman-5-5','成長ホルモン不応性症候群','Growth hormone insensitivity','5-5'),
('shoman-5-6','高プロラクチン血症','Hyperprolactinemia','5-6'),
('shoman-5-7','抗利尿ホルモン（ADH）不適切分泌症候群','Syndrome of inappropriate secretion of antidiuretic hormone','5-7'),
('shoman-5-8','尿崩症','Diabetes insipidus','5-8'),
('shoman-5-9','中枢性塩喪失症候群','Cerebral salt wasting syndrome','5-9'),
('shoman-5-10','甲状腺機能亢進症','hyperthyroidism','5-10'),
('shoman-5-11','甲状腺機能低下症','Hypothyroidism','5-11'),
('shoman-5-13','腺腫様甲状腺腫','Adenomatous goiter','5-13'),
('shoman-5-14','副甲状腺機能亢進症','Hyperparathyroidism','5-14'),
('shoman-5-16','自己免疫性多内分泌腺症候群','Autoimmune polyendocrinopathy','5-16'),
('shoman-5-18','クッシング（Cushing）症候群','Cushing (Cushing) syndrome','5-18'),
('shoman-5-19','慢性副腎皮質機能低下症','Chronic adrenal insufficiency','5-19'),
('shoman-5-20','アルドステロン症','Aldosteronism','5-20'),
('shoman-5-21','見かけの鉱質コルチコイド過剰症候群（AME症候群）','Apparent mineralocorticoid excess syndrome','5-21'),
('shoman-5-22','リドル（Liddle）症候群','Liddle syndrome','5-22'),
('shoman-5-23','低アルドステロン症','Hypoaldosteronism','5-23'),
('shoman-5-24','偽性低アルドステロン症','Pseudohypoaldosteronism','5-24'),
('shoman-5-25','先天性副腎過形成症','Congenital adrenal hyperplasia','5-25'),
('shoman-5-26','思春期早発症','','5-26'),
('shoman-5-27','エストロゲン過剰症（思春期早発症を除く。）','','5-27'),
('shoman-5-28','アンドロゲン過剰症（思春期早発症を除く。）','','5-28'),
('shoman-5-29','低ゴナドトロピン性性腺機能低下症','Hypogonadotropic hypogonadism','5-29'),
('shoman-5-30','高ゴナドトロピン性性腺機能低下症','Hypergonadotropic hypogonadism','5-30'),
('shoman-5-31','性分化疾患','Disorders of sex development','5-31'),
('shoman-5-32','消化管ホルモン産生腫瘍','','5-32'),
('shoman-5-33','グルカゴノーマ','Glucagonoma','5-33'),
('shoman-5-34','高インスリン血性低血糖症','hyperinsulinaemic hypoglycaemia','5-34'),
('shoman-5-35','ビタミンD依存性くる病','Vitamin d-dependent rickets','5-35'),
('shoman-5-36','ビタミンＤ抵抗性骨軟化症','Vitamin d resistant osteomalacia','5-36'),
('shoman-5-37','原発性低リン血症性くる病','Primary hypophosphataemic rickets','5-37'),
('shoman-5-38','脂肪異栄養症（脂肪萎縮症）','Lipodystrophy','5-38'),
('shoman-5-39','多発性内分泌腫瘍','Multiple endocrine neoplasia','5-39'),
('shoman-5-40','多嚢胞性卵巣症候群','Polycystic ovary syndrome','5-40'),
('shoman-6-1','膠原病疾患','Collagen disease disease','6-1'),
('shoman-6-2','血管炎症候群','','6-2'),
('shoman-6-4','皮膚･結合組織疾患','Skin and connective tissue disease','6-4'),
('shoman-6-5','自己炎症性疾患','autoinflammatory disease','6-5'),
('shoman-7-1','糖尿病','Diabetes','7-1'),
('shoman-8-1','アミノ酸代謝異常症','Disorder of amino acid metabolism','8-1'),
('shoman-8-2','有機酸代謝異常症','Disorder of organic acid metabolism','8-2'),
('shoman-8-3','脂肪酸代謝異常症','Disorder of fatty-acid metabolism','8-3'),
('shoman-8-5','糖質代謝異常症','Disorder of carbohydrate metabolism','8-5'),
('shoman-8-7','ペルオキシソーム病','Peroxisomal disease','8-7'),
('shoman-8-8','金属代謝異常症','Disorder of metal metabolism','8-8'),
('shoman-8-9','プリンピリミジン代謝異常症','Disorder of purine and pyrimidine metabolism','8-9'),
('shoman-8-10','ビタミン代謝異常症','Disorder of vitamin metabolism','8-10'),
('shoman-8-11','神経伝達物質異常症','Disorder of neurotransmitter metabolism and transport','8-11'),
('shoman-8-12','脂質代謝異常症','Disorder of lipid metabolism','8-12'),
('shoman-8-13','結合組織異常症','Connective tissue disorder','8-13'),
('shoman-8-14','先天性ポルフィリン症','porphyria','8-14'),
('shoman-8-15','α1-アンチトリプシン欠損症','Alpha-1-antitrypsin deficiency','8-15'),
('shoman-9-1','巨赤芽球性貧血','Megaloblastic anemia','9-1'),
('shoman-9-2','赤芽球癆','pure red cell aplasia','9-2'),
('shoman-9-4','鉄芽球性貧血','Sideroblastic anemia','9-4'),
('shoman-9-5','無トランスフェリン血症','Atransferrinemia','9-5'),
('shoman-9-8','遺伝性溶血性貧血','Hereditary hemolytic anemia','9-8'),
('shoman-9-9','溶血性貧血（脾機能亢進症によるものに限る。）','haemolytic anaemia due to hypersplenism','9-9'),
('shoman-9-10','微小血管障害性溶血性貧血','microangiopathic haemolytic anaemia','9-10'),
('shoman-9-11','真性多血症','Polycythemia vera','9-11'),
('shoman-9-12','家族性赤血球増加症','Familial vera','9-12'),
('shoman-9-13','血小板減少性紫斑病','Thrombocytopenic purpura','9-13'),
('shoman-9-15','血小板減少症（脾機能亢進症によるものに限る。）','Thrombocytopenia (limited to those caused by hypersplenism.)','9-15'),
('shoman-9-16','先天性骨髄不全症候群','','9-16'),
('shoman-9-17','周期性血小板減少症','cyclic thrombocytopenia','9-17'),
('shoman-9-18','メイ・ヘグリン（May-Hegglin）異常症','May‐Hegglin anomaly','9-18'),
('shoman-9-19','本態性血小板血症','essential thrombocythaemia','9-19'),
('shoman-9-20','血小板機能異常症','platelet dysfunction','9-20'),
('shoman-9-21','先天性血液凝固因子異常','Inherited bleeding disorder','9-21'),
('shoman-9-22','先天性プロテインC欠乏症','protein C deficiency','9-22'),
('shoman-9-23','先天性プロテインS欠乏症','protein S deficiency','9-23'),
('shoman-9-24','先天性アンチトロンビン欠乏症','antithrombin deficiency','9-24'),
('shoman-9-25','骨髄線維症','Myelofibrosis','9-25'),
('shoman-10-1','複合免疫不全症','Combined immunodeficiency','10-1'),
('shoman-10-2','免疫不全を伴う特徴的な症候群','immunodeficiency','10-2'),
('shoman-10-3','液性免疫不全を主とする疾患','predominantly antibody deficiency','10-3'),
('shoman-10-4','免疫調節障害','disease of immune dysregulation','10-4'),
('shoman-10-5','原発性食細胞機能不全症および欠損症','','10-5'),
('shoman-10-6','自然免疫異常','defect in innate immunity','10-6'),
('shoman-10-7','先天性補体欠損症','inherited deficiency of complement system','10-7'),
('shoman-10-8','好酸球増加症','hyper eosinophilic syndrome','10-8'),
('shoman-10-9','慢性活動性EBウイルス感染症','Chronic active EB virus infection','10-9'),
('shoman-10-10','後天性免疫不全症','Acquired immune deficiency syndrome','10-10'),
('shoman-10-11','慢性移植片対宿主病','chronic graft-versus-host disease','10-11'),
('shoman-11-2','仙尾部奇形腫','Sacrococcygeal teratoma','11-2'),
('shoman-11-3','脳形成障害','','11-3'),
('shoman-11-4','ジュベール（Joubert）症候群関連疾患','Joubert syndrome related disorders','11-4'),
('shoman-11-5','レット（Rett）症候群','Rett syndrome','11-5'),
('shoman-11-6','神経皮膚症候群','','11-6'),
('shoman-11-7','早老症','','11-7'),
('shoman-11-8','遺伝子異常による白質脳症','Leukoencephalopathy caused by genetic abnormalities','11-8'),
('shoman-11-13','頭蓋骨縫合早期癒合症','craniosynostosis','11-13'),
('shoman-11-15','脳動静脈奇形','Cerebral arteriovenous malformation','11-15'),
('shoman-11-16','海綿状血管腫（脳脊髄）','Cavernous angioma of the brain and spinal cord','11-16'),
('shoman-11-17','脊髄性筋萎縮症','spinal muscular atrophy','11-17'),
('shoman-11-18','先天性ニューロパチー','','11-18'),
('shoman-11-21','シュワルツ・ヤンペル（Schwartz-Jampel）症候群','Schwartz-Jampel syndrome','11-21'),
('shoman-11-22','難治てんかん脳症','','11-22'),
('shoman-11-24','脊髄小脳変性症','Spinocerebellar degeneration','11-24'),
('shoman-11-25','小児交互性片麻痺','alternating hemiplegia of childhood','11-25'),
('shoman-11-26','変形性筋ジストニー','dystonia musculorum deformans','11-26'),
('shoman-11-27','脳の鉄沈着を伴う神経変性疾患','','11-27'),
('shoman-11-28','乳児両側線条体壊死','infantile bilateral striatal necrosis','11-28'),
('shoman-11-29','先天性感染症','','11-29'),
('shoman-11-30','エカルディ・グティエール（Aicardi-Goutieres）症候群','Aicardi-Goutieres syndrome','11-30'),
('shoman-11-32','ラスムッセン（Rasmussen）脳炎','Rasmussen encephalitis','11-32'),
('shoman-11-33','痙攣重積型急性脳症','Acute encephalopathy with biphasic seizures and late reduced diffusion','11-33'),
('shoman-11-34','自己免疫介在性脳炎・脳症','Autoimmune encephalitis','11-34'),
('shoman-11-36','多発性硬化症','multiple sclerosis','11-36'),
('shoman-11-37','慢性炎症性脱髄性多発神経炎','Chronic inflammatory demyelinating polyneuropathy','11-37'),
('shoman-12-1','先天性吸収不全症','','12-1'),
('shoman-12-2','微絨毛封入体病','microvillus inclusion disease','12-2'),
('shoman-12-3','腸リンパ管拡張症','Intestinal Lymphangiectasia','12-3'),
('shoman-12-4','ポリポーシス','Polyposis','12-4'),
('shoman-12-5','周期性嘔吐症候群','Cyclic Vomiting Syndrome','12-5'),
('shoman-12-6','炎症性腸疾患','Inflammatory bowel disease','12-6'),
('shoman-12-7','自己免疫性腸症（IPEX症候群を含む。）','Autoimmune enteropathy (including IPEX syndrome.)','12-7'),
('shoman-12-9','急性肝不全（昏睡型）','Acute Liver Failure','12-9'),
('shoman-12-10','新生児ヘモクロマトーシス','Neonatal Hemochromatosis','12-10'),
('shoman-12-13','肝内胆汁うっ滞性疾患','','12-13'),
('shoman-12-14','先天性肝線維症','Congenital hepatic fibrosis','12-14'),
('shoman-12-15','肝硬変症','Liver Cirrhosis','12-15'),
('shoman-12-16','門脈圧亢進症','portal hypertension','12-16'),
('shoman-12-17','先天性門脈欠損症','Congenital Absence of Portal Vein','12-17'),
('shoman-12-18','門脈・肝動脈瘻','Congenital Hepatoportal Arteriovenous Fistula','12-18'),
('shoman-12-19','クリグラー・ナジャー（Crigler-Najjar）症候群','Crigler-Najjar syndrome','12-19'),
('shoman-12-20','難治性膵炎','Intractable pancreatitis','12-20'),
('shoman-12-21','短腸症','Short Bowel Syndrome','12-21'),
('shoman-12-22','ヒルシュスプルング（Hirschsprung）病及び類縁疾患','Hirschsprung disease and related disease','12-22'),
('shoman-12-23','肝巨大血管腫','giant hepatic haemangiomas','12-23'),
('shoman-13-1','染色体又は遺伝子に変化を伴う症候群','Chromosome abnormality','13-1'),
('shoman-14-1','眼皮膚白皮症（先天性白皮症）','oculocutaneous albinism(congenital albinism)','14-1'),
('shoman-14-6','レックリングハウゼン（Recklinghausen）病（神経線維腫症Ⅰ型）','von Recklinghausen''s disease','14-6'),
('shoman-14-8','外胚葉形成不全','ectodermal dysplsia','14-8'),
('shoman-15-1','胸郭不全症候群','Thoracic insufficiency syndrome','15-1'),
('shoman-15-2','骨系統疾患','Bone disease','15-2'),
('shoman-16-1','脈管奇形','','16-1'),
('shoman-16-2','遺伝性出血性末梢血管拡張症','Hereditary hemorrhagic telangiectasia','16-2'),
('shoman-16-3','カサバッハ・メリット（Kasabach-Merritt）症候群','Kasabach-Merritt syndrome','16-3')) as x(id,name_ja,name_en,source_id)
 on conflict(id) do nothing;
