-- NANDO name imports. CC BY 4.0 NANDO/DBCLS.
-- Place after 012_nando_subtype_identity.sql and prior registry migrations.
insert into public.disease_catalog
 (id,name_ja,name_en,aliases,parent_disease_id,source_url,medical_review_status,published,concept_kind)
select x.id,x.name_ja,x.name_en,x.aliases,x.parent_disease_id,x.source_url,
 'name-only-unreviewed',true,'disease_subtype'
from (values
('nando-19-32-1','Fabry病（古典型）','type 1 Fabry disease',array['type 1 Fabry disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-32-2','Fabry病（亜型）','type 2 Fabry disease',array['type 2 Fabry disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-32-3','Fabry病（顕性ヘテロ接合体）','heterozygous Fabry disease',array['heterozygous Fabry disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-33','シスチン症','Cystinosis',array['Cystinosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-33-1','シスチン症（腎型）','Nephropathic infantile cystinosis',array['Nephropathic infantile cystinosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-33-2','シスチン症（中間型）','Juvenile nephropathic cystinosis',array['Juvenile nephropathic cystinosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-33-3','シスチン症（非腎型）','Ocular cystinosis',array['シスチン症（眼型）','Ocular cystinosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-4','GM1ガングリオシドーシス','GM1 Gangliosidosis',array['GM1 Gangliosidosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-4-1','GM1ガングリオシドーシス（乳児型）','GM1 gangliosidosis type 1',array['GM1 gangliosidosis type 1']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-4-2','GM1ガングリオシドーシス（若年型）','GM1 gangliosidosis type 2',array['GM1 gangliosidosis type 2']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-4-3','GM1ガングリオシドーシス（成人型）','GM1 gangliosidosis type 3',array['GM1 gangliosidosis type 3']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-5','GM2ガングリノシドーシス','GM2 Gangliosidosis',array['GM2 Gangliosidosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-5-1','Tay-Sachs病','Tay–Sachs disease',array['Tay–Sachs disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-5-2','Sandhoff病','Sandhoff disease',array['Sandhoff disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-5-3','AB型','AB variant',array['AB variant']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-6','Krabbe病','Krabbe disease',array['Krabbe disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-6-1','Krabbe病（乳児型）','Infantile Krabbe disease',array['Infantile Krabbe disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-6-2','Krabbe病（若年型）','Late-infantile/juvenile Krabbe disease',array['Late-infantile/juvenile Krabbe disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-6-3','Krabbe病（成人型）','Adult Krabbe disease',array['Adult Krabbe disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-7','異染性白質ジストロフィー','Metachromatic leukodystrophy',array['Metachromatic leukodystrophy']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-7-1','異染性白質ジストロフィー（後期乳児型）','Metachromatic leukodystrophy, late infantile form',array['Metachromatic leukodystrophy, late infantile form']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-7-2','異染性白質ジストロフィー（若年型）','Metachromatic leukodystrophy, juvenile form',array['Metachromatic leukodystrophy, juvenile form']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-7-3','異染性白質ジストロフィー（成人型）','Metachromatic leukodystrophy, adult form',array['Metachromatic leukodystrophy, adult form']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-7-4','サポシンB欠損症','Saposin B deficiency',array['Saposin B deficiency']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-8','マルチプルサルファターゼ欠損症','Multiple sulfatase deficiency',array['Multiple sulfatase deficiency']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-8-1','マルチプルサルファターゼ欠損症(新生児型)','neonatal multiple sulfatase deficiency',array['neonatal multiple sulfatase deficiency']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-8-2','マルチプルサルファターゼ欠損症（乳幼児型）','Late-infantile multiple sulfatase deficiency',array['Late-infantile multiple sulfatase deficiency']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-9','Farber病','Farber disease',array['Farber disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-9-1','Farber病（古典型）','type 1 FD',array['type 1 FD']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-9-2','Farber病（中間型）','type 2 FD',array['type 2 FD']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-9-3','Farber病（軽症型）','type 3 FD',array['type 3 FD']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-9-4','Farber病（新生児型）','type 4 FD',array['type 4 FD']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-9-5','Farber病（神経進行型）','type 5 FD',array['type 5 FD']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-9-6','Farber病（サンドホッフ病合併型）','type 6 FD',array['type 6 FD']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-9-7','Farber病（プロサポシン欠損型）','type 7 FD',array['type 7 FD']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-20-1','副腎白質ジストロフィー（小児大脳型）','Childhood X-linked Adrenoleukodystrophy',array['Childhood X-linked Adrenoleukodystrophy']::text[],'mhlw-0020','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-20-2','副腎白質ジストロフィー（思春期大脳型）','Adolescent-onset X-linked Adrenoleukodystrophy',array['Adolescent-onset X-linked Adrenoleukodystrophy']::text[],'mhlw-0020','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-20-3','副腎白質ジストロフィー（副腎脊髄ニューロパチー）','adrenomyeloneuropathy',array['AMN','adrenomyeloneuropathy']::text[],'mhlw-0020','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-20-4','副腎白質ジストロフィー（成人大脳型）','Adult-onset adrenoleukodystrophy',array['Adult-onset adrenoleukodystrophy']::text[],'mhlw-0020','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-20-5','副腎白質ジストロフィー（小脳・脳幹型）','Atypical X-linked adult adrenoleukodystrophy',array['Atypical X-linked adult adrenoleukodystrophy']::text[],'mhlw-0020','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-20-6','副腎白質ジストロフィー（アジソン型）','Addison''s Disease',array['Addison''s Disease']::text[],'mhlw-0020','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-20-7','副腎白質ジストロフィー（女性発症者）','female adrenoleukodystrophy',array['female adrenoleukodystrophy']::text[],'mhlw-0020','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-205-1','脆弱 X 随伴振戦/失調症候群','Fragile X tremor/ataxia syndrome',array['Fragile X tremor/ataxia syndrome']::text[],'mhlw-0205','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-207-1','総動脈幹遺残症（Ⅰ型）','Truncus arteriosus communis type I',array['Truncus arteriosus communis type I']::text[],'mhlw-0207','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-207-2','総動脈幹遺残症（Ⅱ型）','Truncus arteriosus communis type II',array['Truncus arteriosus communis type II']::text[],'mhlw-0207','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-207-3','総動脈幹遺残症（Ⅲ型）','Truncus arteriosus communis type III',array['Truncus arteriosus communis type III']::text[],'mhlw-0207','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-207-4','総動脈幹遺残症（Ⅳ型）','Truncus arteriosus communis type Ⅳ',array['Truncus arteriosus communis type Ⅳ']::text[],'mhlw-0207','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-209-1','完全大血管転位症（Ⅰ型）','Complete transposition of the great arteries (Group1)',array['Complete transposition of the great arteries (Group1)']::text[],'mhlw-0209','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-209-2','完全大血管転位症（Ⅱ型）','Complete transposition of the great arteries (Group2)',array['Complete transposition of the great arteries (Group2)']::text[],'mhlw-0209','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-209-3','完全大血管転位症（Ⅲ型）','Complete transposition of the great arteries (Group3)',array['Complete transposition of the great arteries (Group3)']::text[],'mhlw-0209','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-209-4','完全大血管転位症（Ⅳ型）','Complete transposition of the great arteries (Group4)',array['Complete transposition of the great arteries (Group4)']::text[],'mhlw-0209','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-21-1','慢性進行性外眼筋麻痺症候群','chronic progressive external ophthalmoplegia',array['chronic progressive external ophthalmoplegia']::text[],'mhlw-0021','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-21-2','リー脳症','Leigh syndrome',array['Leigh syndrome']::text[],'mhlw-0021','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-21-3','ミトコンドリア脳筋症・乳酸アシドーシス・脳卒中様発作症候群','MELAS',array['MELAS']::text[],'mhlw-0021','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-21-4','ミトコンドリア異常を伴うミオクローヌスてんかん','MERRF',array['MERRF']::text[],'mhlw-0021','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-21-5','レーバー病','Leber hereditary optic neuropathy',array['Leber hereditary optic neuropathy']::text[],'mhlw-0021','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-21-6','生化学的異常が明らかになったミトコンドリア病',NULL,array[]::text[],'mhlw-0021','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-21-6-1','複合体Ⅰ欠損症','Mitochondrial complex I deficiency',array['Mitochondrial complex I deficiency']::text[],'mhlw-0021','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-21-6-2','複合体Ⅱ欠損症','Mitochondrial complex II deficiency',array['Mitochondrial complex II deficiency']::text[],'mhlw-0021','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-21-7','原因不明な高乳酸血症',NULL,array[]::text[],'mhlw-0021','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-22-1','もやもや病（両側型）','bilateral moyamoya disease',array['bilateral moyamoya disease']::text[],'mhlw-0022','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-22-2','もやもや病（片側型）','unilateral moyamoya disease',array['unilateral moyamoya disease']::text[],'mhlw-0022','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-220-1','急速進行性糸球体腎炎（MPO-ANCA陽性）','MPO-ANCA positive rapidly progressive glomerulonephritis',array['MPO-ANCA positive rapidly progressive glomerulonephritis']::text[],'mhlw-0220','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-220-2','急速進行性糸球体腎炎（PR3-ANCA陽性）','PR3-ANCA positive rapidly progressive glomerulonephritis',array['PR3-ANCA positive rapidly progressive glomerulonephritis']::text[],'mhlw-0220','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-220-3','急速進行性糸球体腎炎（抗GBM抗体陽性）','Anti-GBM rapidly progressive glomerulonephritis',array['Anti-GBM rapidly progressive glomerulonephritis']::text[],'mhlw-0220','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-222-1','微小変化型ネフローゼ症候群','Minimal change nephrotic syndrome',array['Minimal change nephrotic syndrome']::text[],'mhlw-0222','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-222-2','膜性腎症','Membranous nephropathy',array['Membranous nephropathy']::text[],'mhlw-0222','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-222-3','巣状分節性糸球体硬化症','Focal segmental glomerulosclerosis',array['Focal segmental glomerulosclerosis']::text[],'mhlw-0222','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-222-4','半月体形成性糸球体腎炎','Crescentic Glomerulonephritis',array['Crescentic Glomerulonephritis']::text[],'mhlw-0222','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-222-5','管内増殖性糸球体腎炎','Endocapillary proliferative glomerulonephritis',array['Endocapillary proliferative glomerulonephritis']::text[],'mhlw-0222','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-1','一次性膜性増殖性糸球体腎炎Ⅰ型','MPGN typeⅠ',array['MPGN typeⅠ']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-1-1','メサンギウム細胞軽度増殖性糸球体腎炎','mesangial proliferative GN,slight',array['メサンギウム細胞増殖性糸球体腎炎 1a型','mesangial proliferative GN,slight']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-1-10','急性・びまん型膜性増殖性糸球体腎炎　5c型','MPGN typeⅠ,acute diffuse,marked',array['MPGN typeⅠ,acute diffuse,marked']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-1-11','分葉型膜性増殖性糸球体腎炎','MPGN typeⅠ,lobular',array['MPGN typeⅠ,lobular']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-1-12','終末期型膜性増殖性糸球体腎炎','MPGN typeⅠ,end stage',array['MPGN typeⅠ,end stage']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-1-2','中等度メサンギウム細胞増殖性糸球体腎炎','mesangial proliferative GN,moderate',array['メサンギウム細胞増殖性糸球体腎炎 1b型','mesangial proliferative GN,moderate']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-1-3','慢性・巣状型膜性増殖性糸球体腎炎','MPGN typeⅠ,chronic,focal',array['MPGN typeⅠ,chronic,focal']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-1-4','急性・巣状型膜性増殖性糸球体腎炎','MPGN typeⅠ,acute,focal',array['MPGN typeⅠ,acute,focal']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-1-5','慢性・びまん型膜性増殖性糸球体腎炎　4a型','MPGN typeⅠ,chronic diffuse,slight',array['MPGN typeⅠ,chronic diffuse,slight']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-1-6','慢性・びまん型膜性増殖性糸球体腎炎　4b型','MPGN typeⅠ,chronic diffuse,non-lobular',array['MPGN typeⅠ,chronic diffuse,non-lobular']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-1-7','慢性・びまん型膜性増殖性糸球体腎炎　4c型','MPGN typeⅠ,chronic diffuse,moderate',array['MPGN typeⅠ,chronic diffuse,moderate']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-1-8','急性・びまん型膜性増殖性糸球体腎炎　5a型','MPGN typeⅠ,acute diffuse,endocapillary',array['MPGN typeⅠ,acute diffuse,endocapillary']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-1-9','急性・びまん型膜性増殖性糸球体腎炎　5b型','MPGN typeⅠ,acute diffuse,moderate',array['MPGN typeⅠ,acute diffuse,moderate']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-2','一次性膜性増殖性糸球体腎炎Ⅱ型','MPGN typeⅡ',array['デンスデポジット病','MPGN typeⅡ']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-223-3','一次性膜性増殖性糸球体腎炎Ⅲ型','MPGN typeⅢ',array['MPGN typeⅢ']::text[],'mhlw-0223','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-229-1','自己免疫性肺胞蛋白症','Autoimmune pulmonary alveolar proteinosis',array['Autoimmune pulmonary alveolar proteinosis']::text[],'mhlw-0229','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-229-2','特発性肺胞蛋白症','Idiopathic pulmonary alveolar proteinosis',array['Idiopathic pulmonary alveolar proteinosis']::text[],'mhlw-0229','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-229-3','続発性肺胞蛋白症','Secondary Pulmonary Alveolar Proteinosis',array['Secondary Pulmonary Alveolar Proteinosis']::text[],'mhlw-0229','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-229-4','先天性肺胞蛋白症','Congenital pulmonary alveolar proteinosis',array['Congenital pulmonary alveolar proteinosis']::text[],'mhlw-0229','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-23-1','孤発性クロイツフェルト・ヤコブ病','Sporadic Creutzfeldt-Jakob disease',array['Sporadic Creutzfeldt-Jakob disease']::text[],'mhlw-0023','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-23-2','遺伝性プリオン病','Genetic Prion Diseases',array['Genetic Prion Diseases']::text[],'mhlw-0023','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-23-2-1','家族性CJD','Familial Creutzfeldt-Jakob Disease',array['Familial Creutzfeldt-Jakob Disease']::text[],'mhlw-0023','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-23-2-2','ゲルストマン・ストロイスラー・シャインカー病','Gerstmann-Straussler-Scheinker syndrome',array['Gerstmann-Straussler-Scheinker syndrome']::text[],'mhlw-0023','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-23-2-3','致死性家族性不眠症','fatal familial insomnia',array['fatal familial insomnia']::text[],'mhlw-0023','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-23-3','獲得性クロイツフェルト・ヤコブ病','Acquired Creutzfeldt-Jakob disease',array['Acquired Creutzfeldt-Jakob disease']::text[],'mhlw-0023','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-23-3-1','医原性クロイツフェルト・ヤコブ病','Iatrogenic Creutzfeldt-Jakob disease',array['Iatrogenic Creutzfeldt-Jakob disease']::text[],'mhlw-0023','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-23-3-2','変異型クロイツフェルトヤコブ病','variant Creutzfeldt-Jakob disease',array['variant Creutzfeldt-Jakob disease']::text[],'mhlw-0023','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-230-1','肥満低換気症候群','obesity hypoventilation syndrome',array['obesity hypoventilation syndrome']::text[],'mhlw-0230','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-230-3','特発性中枢性低換気症候群','Idiopathic central hypoventilation syndrome',array['Idiopathic central hypoventilation syndrome']::text[],'mhlw-0230','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-1','ペルオキシソーム形成異常症','Peroxisome biogenesis disorders',array['Peroxisome biogenesis disorders']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-1-1','ツェルベーガー症候群','Zellweger syndrome',array['Zellweger syndrome']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-1-2','新生児型副腎白質ジストロフィー','Neonatal adrenoleukodystrophy',array['Neonatal adrenoleukodystrophy']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-1-3','乳児レフサム病','Infantile Refsum disease',array['Infantile Refsum disease']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-1-4','根性点状軟骨異形成症1型','Rhizomelic chondrodysplasia punctata type 1',array['Rhizomelic chondrodysplasia punctata type 1']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-2','ペルオキシソームβ酸化系酵素欠損症','Peroxisomal beta-oxidation enzyme deficiency',array['Peroxisomal beta-oxidation enzyme deficiency']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-2-1','アシル CoA オキシダーゼ欠損症','Peroxisomal acyl-CoA oxidase deficiency',array['AOX欠損症','Peroxisomal acyl-CoA oxidase deficiency']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-2-2','D-二頭酵素欠損症','D-bifunctional protein deficiency',array['DBP欠損症','D-bifunctional protein deficiency']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-2-3','ステロールキャリアプロテインX欠損症','Sterol carrier protein 2 deficiency',array['SCPx欠損症','Sterol carrier protein 2 deficiency']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-2-4','２-メチルアシルCoAラセマーゼ欠損症','Alpha-methylacyl-CoA racemase deficiency',array['AMACR欠損症','Alpha-methylacyl-CoA racemase deficiency']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-3','レフサム病','Refsum disease',array['Refsum disease']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-4','プラスマローゲン合成系酵素欠損症','Plasmalogen biosynthesis enzyme deficiency',array['Plasmalogen biosynthesis enzyme deficiency']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-4-1','根性点状軟骨異形成症２型','Rhizomelic chondrodysplasia punctata type2',array['Rhizomelic chondrodysplasia punctata type2']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-4-2','根性点状軟骨異形成症３型','Rhizomelic chondrodysplasia punctata type3',array['Rhizomelic chondrodysplasia punctata type3']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-5','原発性高シュウ酸尿症Ⅰ型','Primary hyperoxaluria type 1',array['Primary hyperoxaluria type 1']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-234-6','アカタラセミア','Acatalasemia',array['無カタラーゼ血症','Acatalasemia']::text[],'mhlw-0234','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-238-1','ビタミンＤ抵抗性くる病','Vitamin D-resistant rickets',array['Vitamin D-resistant rickets']::text[],'mhlw-0238','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-239-1','ビタミンD依存症１型','Vitamin D-dependent rickets, type 1',array['Vitamin D-dependent rickets, type 1']::text[],'mhlw-0239','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-239-2','ビタミンD依存症２型','Vitamin D-dependent rickets, type 2',array['Vitamin D-dependent rickets, type 2']::text[],'mhlw-0239','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-24-1','亜急性硬化性全脳炎（典型）',NULL,array[]::text[],'mhlw-0024','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-24-1-1','急速進行型',NULL,array[]::text[],'mhlw-0024','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-24-1-2','亜急性進行型',NULL,array[]::text[],'mhlw-0024','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-24-1-3','緩徐進行型',NULL,array[]::text[],'mhlw-0024','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-24-1-4','慢性再発−寛解型',NULL,array[]::text[],'mhlw-0024','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-24-2','亜急性硬化性全脳炎（非典型）','Atypical subacute sclerosing panencephalitis',array['Atypical subacute sclerosing panencephalitis']::text[],'mhlw-0024','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-24-2-1','症状が痙攣のみの例',NULL,array[]::text[],'mhlw-0024','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-24-2-2','Jabbour 分類の I 期が 遷延する例',NULL,array[]::text[],'mhlw-0024','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-24-2-3','乳児あるいは成人例',NULL,array[]::text[],'mhlw-0024','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-240-1','PAH欠損症','Phenylalanine Hydroxylase Deficiency',array['Phenylalanine Hydroxylase Deficiency']::text[],'mhlw-0240','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-240-2','BH4欠損症','Tetrahydrobiopterin deficiency',array['Tetrahydrobiopterin deficiency']::text[],'mhlw-0240','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-240-3','BH4反応性高Phe血症','Tetrahydrobiopterin responsive hyperphenylalaninemia',array['BH4反応性高フェニルアラニン血症','Tetrahydrobiopterin responsive hyperphenylalaninemia']::text[],'mhlw-0240','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-246-1','MCM欠損症','Methylmalonyl-Coenzyme A mutase deficiency',array['Methylmalonyl-Coenzyme A mutase deficiency']::text[],'mhlw-0246','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-246-2','メチルマロン酸血症（cblA型）','Methylmalonic acidemia type cb1A',array['cb1A','Methylmalonic acidemia type cb1A']::text[],'mhlw-0246','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-246-3','メチルマロン酸血症（cblB型）','Methylmalonic acidemia type cb1B',array['cb1B','Methylmalonic acidemia type cb1B']::text[],'mhlw-0246','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-246-4','メチルマロン酸血症（cblD型）','Methylmalonic acidemia type cb1D',array['cb1D','Methylmalonic acidemia type cb1D']::text[],'mhlw-0246','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-251-1','CPSI欠損症','Carbamoyl phosphate synthetase I deficiency',array['Carbamoyl phosphate synthetase I deficiency']::text[],'mhlw-0251','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-251-2','OTC欠損症','Ornithine transcarbamylase deficiency',array['Ornithine transcarbamylase deficiency']::text[],'mhlw-0251','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-251-3','古典型シトルリン血症','classic citrullinemia',array['Ⅰ型シトルリン血症','classic citrullinemia']::text[],'mhlw-0251','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-251-4','アルギニノコハク酸尿症','Argininosuccinic aciduria',array['Argininosuccinic aciduria']::text[],'mhlw-0251','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-251-5','アルギニン血症','Argininemia',array['Argininemia']::text[],'mhlw-0251','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-251-6','NAGS欠損症','NAGS deficiency',array['NAGS deficiency']::text[],'mhlw-0251','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-254-1','急性間欠性ポルフィリン症','Acute intermittent porphyria',array['Acute intermittent porphyria']::text[],'mhlw-0254','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-254-2','遺伝性コプロポルフィリン症','Hereditary coproporphyria',array['Hereditary coproporphyria']::text[],'mhlw-0254','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-254-3','異型ポルフィリン症','Variegate porphyria',array['Variegate porphyria']::text[],'mhlw-0254','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-254-4','赤芽球性プロトポルフィリン症','Erythropoietic protoporphyria',array['骨髄性プロトポルフィリン症','Erythropoietic protoporphyria']::text[],'mhlw-0254','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-254-5','晩発性皮膚ポルフィリン症','Porphyria cutanea tarda',array['Porphyria cutanea tarda']::text[],'mhlw-0254','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-254-6','先天性骨髄性ポルフィリン症','Congenital erythropoietic porphyria',array['Congenital erythropoietic porphyria']::text[],'mhlw-0254','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-254-7','X連鎖優性プロトポルフィリン症','X-linked dominant protoporphyria',array['X-linked dominant protoporphyria']::text[],'mhlw-0254','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-254-8','肝性骨髄性ポルフィリン症','Hepatoerythropoietic porphyria',array['Hepatoerythropoietic porphyria']::text[],'mhlw-0254','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-255-1','ホロカルボキシラーゼ合成酵素欠損症','Holocarboxylase synthetase deficiency',array['HCS欠損症','Holocarboxylase synthetase deficiency']::text[],'mhlw-0255','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-255-2','ビオチニダーゼ欠損症','Biotinidase deficiency',array['Biotinidase deficiency']::text[],'mhlw-0255','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-256-1','筋型糖原病0型','Glycogen storage diseases type 0',array['グリコーゲン合成酵素欠損症','Glycogen storage diseases type 0']::text[],'mhlw-0256','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-256-10','筋型糖原病XI型','Glycogen storage diseases type XI',array['Kanno病','Glycogen storage diseases type XI']::text[],'mhlw-0256','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-256-11','筋型糖原病XII型','Glycogen storage diseases type XII',array['Glycogen storage diseases type XII']::text[],'mhlw-0256','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-256-12','筋型糖原病XIII型','Glycogen storage diseases type XIII',array['Glycogen storage diseases type XIII']::text[],'mhlw-0256','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-256-13','筋型糖原病XIV型','Glycogen storage diseases type XIV',array['Glycogen storage diseases type XIV']::text[],'mhlw-0256','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-256-14','筋型糖原病XV型','Glycogen storage diseases type XV',array['Glycogen storage diseases type XV']::text[],'mhlw-0256','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-256-2','筋型糖原病II型','Glycogen storage diseases type II',array['Pompe病','Glycogen storage diseases type II']::text[],'mhlw-0256','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-256-3','筋型糖原病III型','Glycogen storage diseases type III',array['Cori病','Glycogen storage diseases type III']::text[],'mhlw-0256','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-256-4','筋型糖原病IV型','Glycogen storage diseases type IV',array['Andersen病','Glycogen storage diseases type IV']::text[],'mhlw-0256','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-256-5','筋型糖原病V型','Glycogen storage diseases type V',array['McArdle病','Glycogen storage diseases type V']::text[],'mhlw-0256','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-256-6','筋型糖原病VII型','Glycogen storage diseases type VII',array['Tarui病','Glycogen storage diseases type VII']::text[],'mhlw-0256','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-256-7','筋型糖原病IXd型','Glycogen storage diseases type IXd',array['Glycogen storage diseases type IXd']::text[],'mhlw-0256','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-256-8','PGK欠損症','Phosphoglycerate kinase deficiency',array['Phosphoglycerate kinase deficiency']::text[],'mhlw-0256','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-256-9','筋型糖原病X型','Glycogen storage diseases type X',array['Glycogen storage diseases type X']::text[],'mhlw-0256','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-257-1','糖原病Ⅰ-Ⅲ-Ⅵ-Ⅸ型','Glycogen storage disease type I-III-VI-IX',array['Glycogen storage disease type I-III-VI-IX']::text[],'mhlw-0257','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-257-1-1','糖原病Ⅰa型','Glycogen storage disease type Ia',array['グルコース-6-ホスファターゼ欠損症','Glycogen storage disease type Ia']::text[],'mhlw-0257','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-257-1-10','糖原病Ⅸc型','Glycogen storage disease type Ⅸc',array['ホスホリラーゼ欠損症（γサブユニット異常症）','Glycogen storage disease type Ⅸc']::text[],'mhlw-0257','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-257-1-2','糖原病Ⅰb型','Glycogen storage disease type Ib',array['グルコース-6-ホスファターゼトランスポーター異常症','Glycogen storage disease type Ib']::text[],'mhlw-0257','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-257-1-3','糖原病Ⅲa型','GSD type IIIa',array['グリコーゲン脱分枝酵素欠損症','GSD type IIIa']::text[],'mhlw-0257','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-257-1-4','糖原病Ⅲb型','GSD type IIIb',array['グリコーゲン脱分枝酵素欠損症','GSD type IIIb']::text[],'mhlw-0257','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-257-1-5','糖原病Ⅲc型','GSD type IIIc',array['グルコシダーゼ欠損症','GSD type IIIc']::text[],'mhlw-0257','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-257-1-6','糖原病Ⅲd型','GSD type IIId',array['トランスフェラーゼ欠損症','GSD type IIId']::text[],'mhlw-0257','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-257-1-7','糖原病Ⅵ型','Glycogen storage disease type VI',array['肝グリコーゲンホスホリラーゼ欠損症','ハース病','Glycogen storage disease type VI']::text[],'mhlw-0257','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-257-1-8','糖原病Ⅸa型','Glycogen storage disease type Ⅸa',array['ホスホリラーゼ欠損症（αサブユニット異常症）','Glycogen storage disease type Ⅸa']::text[],'mhlw-0257','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-257-1-9','糖原病Ⅸb型','Glycogen storage disease type Ⅸb',array['ホスホリラーゼ欠損症（βサブユニット異常症）','Glycogen storage disease type Ⅸb']::text[],'mhlw-0257','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-257-2','Ⅳ型糖原病','Glycogen storage disease type IV',array['Glycogen storage disease type IV']::text[],'mhlw-0257','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-265-1','先天性全身性脂肪萎縮症','Generalized congenital lipodystrophy',array['Generalized congenital lipodystrophy']::text[],'mhlw-0265','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-265-2','後天性全身性脂肪萎縮症','Acquired generalized lipodystrophy',array['Acquired generalized lipodystrophy']::text[],'mhlw-0265','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-265-3','家族性部分性脂肪萎縮症','Familial partial lipodystrophy',array['Familial partial lipodystrophy']::text[],'mhlw-0265','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-265-4','後天性部分性脂肪萎縮症','Partial acquired lipodystrophy',array['Partial acquired lipodystrophy']::text[],'mhlw-0265','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-266-1','家族性地中海熱典型例',NULL,array[]::text[],'mhlw-0266','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-266-2','家族性地中海熱非典型例','Atypical familial Mediterranean fever',array['Atypical familial Mediterranean fever']::text[],'mhlw-0266','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-27-1','家族性特発性基底核石灰化症','Familial idiopathic basal ganglia calcification',array['Familial idiopathic basal ganglia calcification']::text[],'mhlw-0027','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-275-1','タナトフォリック骨異形成症１型','Thanatophoric dysplasia type 1',array['Thanatophoric dysplasia type 1']::text[],'mhlw-0275','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-275-2','タナトフォリック骨異形成症２型','Thanatophoric dysplasia type 2',array['Thanatophoric dysplasia type 2']::text[],'mhlw-0275','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-277-1','リンパ管腫症','Lymphangiomatosis',array['Lymphangiomatosis']::text[],'mhlw-0277','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-277-2','ゴーハム病','Gorham disease',array['Gorham disease']::text[],'mhlw-0277','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-28-1-1','免疫グロブリン性アミロイドーシス','AL amyloidosis',array['AL amyloidosis']::text[],'mhlw-0028','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-28-1-2','老人性トランスサイレチン型アミロイドーシス','senile systemic amyloidosis',array['senile systemic amyloidosis']::text[],'mhlw-0028','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-28-1-3','反応性AAアミロイドーシス','Reactive AA amyloidosis',array['Reactive AA amyloidosis']::text[],'mhlw-0028','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-28-2','家族性アミロイドニューロパチー','Familial amyloid polyneuropathy',array['Familial amyloid polyneuropathy']::text[],'mhlw-0028','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-282-1','先天性赤血球形成異常性貧血 Type I','Congenital dyserythropoietic anemia type I',array['Congenital dyserythropoietic anemia type I']::text[],'mhlw-0282','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-282-2','先天性赤血球形成異常性貧血 Type II','Congenital dyserythropoietic anemia type II',array['Congenital dyserythropoietic anemia type II']::text[],'mhlw-0282','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-282-3','先天性赤血球形成異常性貧血 Type III','Congenital dyserythropoietic anemia type III',array['Congenital dyserythropoietic anemia type III']::text[],'mhlw-0282','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-287-1','最重症型エプスタイン症候群','severe Epstein syndrome',array['severe Epstein syndrome']::text[],'mhlw-0287','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-287-2','中等症エプスタイン症候群',NULL,array[]::text[],'mhlw-0287','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-288-1','自己免疫性後天性凝固第 XIII/13 因子欠乏症','Autoimmune Hemorrhaphilia XIII/13',array['Autoimmune Hemorrhaphilia XIII/13']::text[],'mhlw-0288','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-288-2','自己免疫性後天性凝固第 VIII/8 因子欠乏症','Acquired hemophilia A',array['後天性血友病A','Acquired hemophilia A']::text[],'mhlw-0288','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-288-3','自己免疫性後天性フォンウィルブランド因子欠乏症','Acquired von Willebrand disease',array['自己免疫性後天性フォンウィルブランド病','AVWD','Acquired von Willebrand disease']::text[],'mhlw-0288','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-288-4','自己免疫性後天性凝固第 V/5 因子欠乏症','Acquired Factor V Inhibitor',array['Acquired Factor V Inhibitor']::text[],'mhlw-0288','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-291-1','直腸下部型ヒルシュスプルング病','Short-Segment Hirschsprung''s Disease',array['Short-Segment Hirschsprung''s Disease']::text[],'mhlw-0291','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-291-2','S状結腸型ヒルシュスプルング病','rectosigmoid Hirschsprung''s disease',array['rectosigmoid Hirschsprung''s disease']::text[],'mhlw-0291','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-291-3','左右結腸型ヒルシュスプルング病','Long-segment Hirschsprung''s disease',array['Long-segment Hirschsprung''s disease']::text[],'mhlw-0291','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-291-4','全結腸型ヒルシュスプルング病','Entire colon Hirschsprung disease',array['Entire colon Hirschsprung disease']::text[],'mhlw-0291','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-291-5','小腸型ヒルシュスプルング病','Extensive aganglionosis Hirschsprung disease',array['Extensive aganglionosis Hirschsprung disease']::text[],'mhlw-0291','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-296-1','Ⅰ型胆道閉鎖症','type I biliary atresia',array[]::text[],'mhlw-0296','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-296-2','Ⅰcyst型胆道閉鎖症','type I cystic biliary atresia',array['type I cystic biliary atresia']::text[],'mhlw-0296','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-296-3','Ⅱ型胆道閉鎖症','type II biliary atresia',array['type II biliary atresia']::text[],'mhlw-0296','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-296-4','Ⅲ型胆道閉鎖症','type III biliary atresia',array['type III biliary atresia']::text[],'mhlw-0296','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-297-1','アラジール症候群典型例',NULL,array[]::text[],'mhlw-0297','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-297-2','アラジール症候群非典型例','Atypical Alagille Syndrome',array['Atypical Alagille Syndrome']::text[],'mhlw-0297','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-3-1','脊髄性筋萎縮症 I 型','Werdnig-Hoffmann disease',array['ウェルドニッヒ・ホフマン病','Werdnig-Hoffmann disease']::text[],'sma','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-3-2','脊髄性筋萎縮症 II 型','Dubowitz disease',array['デュボビッツ病','Dubowitz disease']::text[],'sma','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-3-3','脊髄性筋萎縮症 III 型','Kugelberg-Welander disease',array['クーゲンベルグ・ウェランダー病','Kugelberg-Welander disease']::text[],'sma','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-3-4','脊髄性筋萎縮症 IV 型','Spinal muscular atrophy type4',array['Spinal muscular atrophy type4']::text[],'sma','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-30-1','三好型ミオパチー','Miyoshi myopathy',array['Miyoshi myopathy']::text[],'mhlw-0030','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-30-2','縁取り空胞を伴う遠位型ミオパチー','Distal myopathy with rimmed vacuoles',array['Distal myopathy with rimmed vacuoles']::text[],'mhlw-0030','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-30-3','眼咽頭遠位型ミオパチー','Oculopharyngodistal myopathy',array['Oculopharyngodistal myopathy']::text[],'mhlw-0030','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-300-1','IgG4関連疾患包括','IgG4-related disease',array['IgG4-related disease']::text[],'mhlw-0300','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-300-2','自己免疫性膵炎','Autoimmune pancreatitis',array['Autoimmune pancreatitis']::text[],'mhlw-0300','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json')
) as x(id,name_ja,name_en,aliases,parent_disease_id,source_url)
on conflict (id) do nothing;
