-- NANDO name imports. CC BY 4.0 NANDO/DBCLS.
-- Place after 012_nando_subtype_identity.sql and prior registry migrations.
insert into public.disease_catalog
 (id,name_ja,name_en,aliases,parent_disease_id,source_url,medical_review_status,published,concept_kind)
select x.id,x.name_ja,x.name_en,x.aliases,x.parent_disease_id,x.source_url,
 'name-only-unreviewed',true,'disease_subtype'
from (values
('nando-300-2-1','びまん型自己免疫性膵炎','diffuse-type autoimmune pancreatitis',array['diffuse-type autoimmune pancreatitis']::text[],'mhlw-0300','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-300-2-2','限局型自己免疫性膵炎','focal-type autoimmune pancreatitis',array['focal-type autoimmune pancreatitis']::text[],'mhlw-0300','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-300-3','IgG4関連硬化性胆管炎','IgG4-related sclerosing cholangitis',array['IgG4-related sclerosing cholangitis']::text[],'mhlw-0300','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-300-4','IgG4関連涙腺・眼窩および唾液腺病変','IgG4 related dacryoadenitis and sialadenitis',array['IgG4 related dacryoadenitis and sialadenitis']::text[],'mhlw-0300','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-300-5','IgG4関連腎臓病','IgG4-related kidney disease',array['IgG4-related kidney disease']::text[],'mhlw-0300','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-301-1','卵黄様黄斑ジストロフィー','Vitelliform macular dystrophy',array['ベスト病','Vitelliform macular dystrophy']::text[],'mhlw-0301','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-301-2','Stargardt病','Stargardt disease',array['Stargardt disease']::text[],'mhlw-0301','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-301-3','オカルト黄斑ジストロフィー','Occult macular dystrophy',array['Occult macular dystrophy']::text[],'mhlw-0301','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-301-4','錐体ジストロフィー、および錐体杆体ジストロフィー','Cone-rod dystrophy and cone dystrophy',array['Cone-rod dystrophy and cone dystrophy']::text[],'mhlw-0301','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-301-4-1','錐体ジストロフィー','Cone dystrophy',array['Cone dystrophy']::text[],'mhlw-0301','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-301-4-2','錐体杆体ジストロフィー','Cone-rod dystrophy',array['Cone-rod dystrophy']::text[],'mhlw-0301','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-301-5','X連鎖性若年網膜分離症','X-linked juvenile retinoschisis',array['X染色体若年網膜分離症','X-linked juvenile retinoschisis']::text[],'mhlw-0301','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-301-6','中心性輪紋状脈絡膜ジストロフィー','Central areolar choroidal dystrophy',array['Central areolar choroidal dystrophy']::text[],'mhlw-0301','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-303-1','アッシャー症候群１型','Usher Syndrome Type I',array['Usher Syndrome Type I']::text[],'mhlw-0303','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-303-2','アッシャー症候群２型','Usher Syndrome Type II',array['Usher Syndrome Type II']::text[],'mhlw-0303','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-303-3','アッシャー症候群３型','Usher Syndrome Type III',array['Usher Syndrome Type III']::text[],'mhlw-0303','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-308-1','皮質下嚢胞をもつ大頭型白質脳症','Megalencephalic leukoencephalopathy with subcortical cysts',array['Megalencephalic leukoencephalopathy with subcortical cysts']::text[],'mhlw-0308','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-308-2','白質消失病','Leukoencephalopathy with vanishing white matter',array['Leukoencephalopathy with vanishing white matter']::text[],'mhlw-0308','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-308-3','卵巣機能障害を伴う進行性白質脳症','Leukoencephalopathy, progressive, with ovarian failure',array['Leukoencephalopathy, progressive, with ovarian failure']::text[],'mhlw-0308','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-309-1','ウンフェルリヒト・ルンドボルグ病','Unverricht-Lundborg disease',array['Unverricht-Lundborg disease']::text[],'mhlw-0309','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-309-2','ラフォラ病','Lafora disease',array['Lafora disease']::text[],'mhlw-0309','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-309-3','良性成人型家族性ミオクローヌスてんかん','benign adult familial myoclonus epilepsy',array['benign adult familial myoclonus epilepsy']::text[],'mhlw-0309','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-310-1','1q部分重複症候群','Partial trisomy 1q',array['Partial trisomy 1q']::text[],'mhlw-0310','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-310-2','9q34欠失症候群','9q34 deletion syndrome',array['9q34 deletion syndrome']::text[],'mhlw-0310','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-310-3','コルネリア・デランゲ症候群','Cornelia de lange syndrome',array['Cornelia de lange syndrome']::text[],'mhlw-0310','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-310-4','スミス・レムリ・オピッツ症候群','Smith-lemli-opitz syndrome',array['Smith-lemli-opitz syndrome']::text[],'mhlw-0310','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-315-1','ネイルパテラ症候群','nail-patella syndrome',array['爪膝蓋骨症候群','nail-patella syndrome']::text[],'mhlw-0315','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-315-2','ＬＭＸ１Ｂ関連腎症','LMX1B-Associated Nephropathy',array['LMX1B-Associated Nephropathy']::text[],'mhlw-0315','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-316-1','CPT1欠損症','Carnitine Palmitoyltransferase I deficiency',array['カルニチンパルミトイルトランスフェラーゼⅠ欠損症','Carnitine Palmitoyltransferase I deficiency']::text[],'mhlw-0316','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-316-2','CPT2欠損症','Carnitine Palmitoyltransferase II deficiency',array['カルニチンパルミトイルトランスフェラーゼⅡ欠損症','Carnitine Palmitoyltransferase II deficiency']::text[],'mhlw-0316','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-316-3','CACT欠損症','Carnitine-acylcarnitine translocase deficiency',array['Carnitine-acylcarnitine translocase deficiency']::text[],'mhlw-0316','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-316-4','OCTN-2異常症','Systemic primary carnitine deficiency',array['全身性カルニチン欠乏症','Systemic primary carnitine deficiency']::text[],'mhlw-0316','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-317-1','新生児期発症型三頭酵素欠損症','Trifunctional protein deficiency,lethal type',array['Trifunctional protein deficiency,lethal type']::text[],'mhlw-0317','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-317-2','乳幼児期発症型三頭酵素欠損症','Trifunctional protein deficiency,intermediate type',array['Trifunctional protein deficiency,intermediate type']::text[],'mhlw-0317','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-317-3','遅発型三頭酵素欠損症','Trifunctional protein deficiency,myopathic type',array['Trifunctional protein deficiency,myopathic type']::text[],'mhlw-0317','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-318-1','新生児肝内胆汁うっ滞症','neonatal intrahepatic cholestasis caused by citrin deficiency',array['neonatal intrahepatic cholestasis caused by citrin deficiency']::text[],'mhlw-0318','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-318-2','成人発症Ⅱ型シトルリン血症','adult-onset type II citrullinemia',array['adult-onset type II citrullinemia']::text[],'mhlw-0318','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-318-3','適応・代償期シトリン欠損症','Failure to thrive and dyslipidemia caused by citrin deficiency',array['Failure to thrive and dyslipidemia caused by citrin deficiency']::text[],'mhlw-0318','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-32-2','過剰自己貪食を伴うＸ連鎖性ミオパチー','X-linked Myopathy with excessive autophagy',array['X-linked Myopathy with excessive autophagy']::text[],'mhlw-0032','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-321-1','新生児型非ケトーシス型高グリシン血症','Neonatal nonketotic hyperglycinemia',array['Neonatal nonketotic hyperglycinemia']::text[],'mhlw-0321','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-321-2','乳児型非ケトーシス型高グリシン血症','infantile nonketotic hyperglycinemia',array['infantile nonketotic hyperglycinemia']::text[],'mhlw-0321','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-324-1','メチルグルタコン酸尿症I型','3-methylglutaconic aciduria type I',array['メチルグルタコニルCoAヒドラターゼ欠損症','3-methylglutaconic aciduria type I']::text[],'mhlw-0324','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-324-2','メチルグルタコン酸尿症II型','3-methylglutaconicaciduria type II',array['Barth症候群','3-methylglutaconicaciduria type II']::text[],'mhlw-0324','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-324-3','メチルグルタコン酸尿症III型','3-methylglutaconic aciduria type III',array['Costeff症候群','3-methylglutaconic aciduria type III']::text[],'mhlw-0324','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-325-1','NLRC４異常症','NLRC4 inflammasomopathies',array['NLRC4 inflammasomopathies']::text[],'mhlw-0325','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-325-2','ADA２欠損症','Adenosine deaminase 2 deficiency',array['Adenosine deaminase 2 deficiency']::text[],'mhlw-0325','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-325-3','エカルディ・グティエール症候群','Aicardi-Goutières　Syndrome',array['Aicardi-Goutières　Syndrome']::text[],'mhlw-0325','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-325-4','A20ハプロ不全症','A20 haploinsufficiency',array['A20 haploinsufficiency']::text[],'mhlw-0325','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-330-1','先天性気管狭窄症','Congenital tracheal stenosis',array['Congenital tracheal stenosis']::text[],'mhlw-0330','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-330-2','先天性声門下狭窄症','Congenital Subglottic Stenosis',array['Congenital Subglottic Stenosis']::text[],'mhlw-0330','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-34-1','神経線維腫症Ⅰ型','Neurofibromatosis Type 1',array['Neurofibromatosis Type 1']::text[],'mhlw-0034','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-34-2','神経線維腫症Ⅱ型','Neurofibromatosis Type 2',array['Neurofibromatosis Type 2']::text[],'mhlw-0034','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-35-1','天疱瘡（尋常性）',NULL,array[]::text[],'mhlw-0035','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-35-2','天疱瘡（落葉状）','pemphigus foliaceus',array['pemphigus foliaceus']::text[],'mhlw-0035','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-35-3','天疱瘡（腫瘍随伴性）','Paraneoplastic pemphigus',array['Paraneoplastic pemphigus']::text[],'mhlw-0035','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-35-4','天疱瘡（増殖性）','pemphigus vegetans',array['pemphigus vegetans']::text[],'mhlw-0035','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-35-5','天疱瘡（紅斑性）','Pemphigus erythematosus',array['Pemphigus erythematosus']::text[],'mhlw-0035','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-36-1','表皮水疱症（単純型）','Epidermolysis bullosa simplex',array['Epidermolysis bullosa simplex']::text[],'mhlw-0036','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-36-2','表皮水疱症（接合部型）','Junctional epidermolysis bullosa',array['Junctional epidermolysis bullosa']::text[],'mhlw-0036','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-36-3','表皮水疱症（優性栄養障害型）','Dominant dystrophic epidermolysis bullosa',array['Dominant dystrophic epidermolysis bullosa']::text[],'mhlw-0036','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-36-4','表皮水疱症（劣性栄養障害型）','Recessive dystrophic epidermolysis bullosa',array['Recessive dystrophic epidermolysis bullosa']::text[],'mhlw-0036','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-36-5','表皮水疱症（キンドラー症候群）','Kindler syndrome',array['Kindler syndrome']::text[],'mhlw-0036','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-37-1','急性汎発性膿疱性乾癬','Acute generalized pustular psoriasis',array['von Zumbusch 型','Acute generalized pustular psoriasis']::text[],'mhlw-0037','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-37-2','小児汎発性膿疱性乾癬','Infantile generalized pustular psoriasis',array['Infantile generalized pustular psoriasis']::text[],'mhlw-0037','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-37-3','疱疹状膿痂疹','Impetigo Herpesformis',array['Impetigo Herpesformis']::text[],'mhlw-0037','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-37-4','稽留性肢端皮膚炎の汎発化','Acrodermatitis Continua of Hallopeau',array['Acrodermatitis Continua of Hallopeau']::text[],'mhlw-0037','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-39-1','中毒性表皮壊死症（SJS進展型）','toxic epidermal necrolysis with spots',array['toxic epidermal necrolysis with spots']::text[],'mhlw-0039','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-39-2','中毒性表皮壊死症（びまん性紅班進展型）','toxic epidermal necrolysis without spots',array['toxic epidermal necrolysis without spots']::text[],'mhlw-0039','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-39-3','中毒性表皮壊死症（特殊型）',NULL,array[]::text[],'mhlw-0039','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-39-4','中毒性表皮壊死症（不全型）',NULL,array[]::text[],'mhlw-0039','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-40-1','高安動脈炎（Ⅰ型）','Type I Takayasu arteritis',array['Type I Takayasu arteritis']::text[],'mhlw-0040','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-40-2','高安動脈炎（Ⅱa型）','Type Ⅱa Takayasu arteritis',array['Type Ⅱa Takayasu arteritis']::text[],'mhlw-0040','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-40-3','高安動脈炎（Ⅱb型）','Type Ⅱb Takayasu arteritis',array['Type Ⅱb Takayasu arteritis']::text[],'mhlw-0040','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-40-4','高安動脈炎（Ⅲ型）','Type Ⅲ Takayasu arteritis',array['Type Ⅲ Takayasu arteritis']::text[],'mhlw-0040','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-40-5','高安動脈炎（Ⅳ型）','Type Ⅳ Takayasu arteritis',array['Type Ⅳ Takayasu arteritis']::text[],'mhlw-0040','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-40-6','高安動脈炎（Ⅴ型）','Type Ⅴ Takayasu arteritis',array['Type Ⅴ Takayasu arteritis']::text[],'mhlw-0040','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-41-1','巨細胞性動脈炎（側頭動脈・顎動脈・眼動脈などの頭蓋領域の動脈に限局）',NULL,array[]::text[],'mhlw-0041','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-41-2','巨細胞性動脈炎（頭蓋領域の動脈に限局せず大動脈・総頸動脈・鎖骨下動脈などにも分布）',NULL,array[]::text[],'mhlw-0041','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-48-1','動静脈血栓症','Thrombotic Antiphospholipid Syndrome',array['Thrombotic Antiphospholipid Syndrome']::text[],'mhlw-0048','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-48-2','妊娠合併症','Antiphospholipid Syndrome and Pregnancy',array['Antiphospholipid Syndrome and Pregnancy']::text[],'mhlw-0048','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-48-3','劇症型','Catastrophic antiphospholipid syndrome',array['Catastrophic antiphospholipid syndrome']::text[],'mhlw-0048','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-48-4','抗リン脂質抗体関連疾患',NULL,array[]::text[],'mhlw-0048','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-50-1','皮膚筋炎','Dermatomyositis',array['Dermatomyositis']::text[],'mhlw-0050','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-50-2','無筋症性皮膚筋炎','amyopathic dermatomyositis',array['amyopathic dermatomyositis']::text[],'mhlw-0050','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-50-3','多発性筋炎','Polymyositis',array['Polymyositis']::text[],'mhlw-0050','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-53-1','一次性シェーグレン症候群','Primary Sjogren syndrome',array['Primary Sjogren syndrome']::text[],'mhlw-0053','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-53-2','二次性シェーグレン症候群','Secondary Sjogren Syndrome',array['Secondary Sjogren Syndrome']::text[],'mhlw-0053','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-58-1','非閉塞性肥大型心筋症','hypertrophic nonobstructive cardiomyopathy',array['hypertrophic nonobstructive cardiomyopathy']::text[],'mhlw-0058','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-58-2','閉塞性肥大型心筋症','hypertrophic obstructive cardiomyopathy',array['hypertrophic obstructive cardiomyopathy']::text[],'mhlw-0058','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-58-3','心室中部閉塞性肥大型心筋症','mid-ventricular obstruction',array['mid-ventricular obstruction']::text[],'mhlw-0058','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-58-4','心尖部肥大型心筋症','apical hypertrophic cardiomyopathy',array['apical hypertrophic cardiomyopathy']::text[],'mhlw-0058','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-58-5','拡張相肥大型心筋症','dilated phase of hypertrophic cardiomyopathy',array['dilated phase of hypertrophic cardiomyopathy']::text[],'mhlw-0058','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-59-1','特発性拘束型心筋症','Idiopathic restrictive cardiomyopathy',array['Idiopathic restrictive cardiomyopathy']::text[],'mhlw-0059','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-59-2','二次性拘束型心筋症','Secondary restrictive cardiomyopathy',array['Secondary restrictive cardiomyopathy']::text[],'mhlw-0059','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-60-1','特発性再生不良性貧血','Idiopathic aplastic anemia',array['Idiopathic aplastic anemia']::text[],'mhlw-0060','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-60-2','二次性再生不良性貧血','Secondary aplastic anemia',array['Secondary aplastic anemia']::text[],'mhlw-0060','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-60-3','特殊型再生不良性貧血',NULL,array[]::text[],'mhlw-0060','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-60-3-1','肝炎後','Hepatitis-Associated Aplastic Anemia',array['肝炎後再生不良性貧血','Hepatitis-Associated Aplastic Anemia']::text[],'mhlw-0060','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-60-3-2','再生不良性貧血-PNH症候群','aplastic anaemia--paroxysmal nocturnal haemoglobinuria syndrome',array['aplastic anaemia--paroxysmal nocturnal haemoglobinuria syndrome']::text[],'mhlw-0060','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-60-3-3','MDSとの境界型',NULL,array[]::text[],'mhlw-0060','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-60-4','先天性再生不良性貧血','Congenital aplastic anemia',array['Congenital aplastic anemia']::text[],'mhlw-0060','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-60-4-2','先天性角化異常症','dyskeratosis congenita',array['dyskeratosis congenita']::text[],'mhlw-0060','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-61-1','温式自己免疫性溶血性貧血','Warm autoimmune hemolytic anemia',array['Warm autoimmune hemolytic anemia']::text[],'mhlw-0061','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-61-2','寒冷凝集素症','cold agglutinin disease',array['cold agglutinin disease']::text[],'mhlw-0061','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-61-3','寒冷ヘモグロビン尿症','paroxysmal cold haemoglobinuria',array['paroxysmal cold haemoglobinuria']::text[],'mhlw-0061','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-61-4','混合型','Mixed-type autoimmune hemolytic anemia',array['Mixed-type autoimmune hemolytic anemia']::text[],'mhlw-0061','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-61-5','エヴァンズ症候群','Evans syndrome',array['Evans syndrome']::text[],'mhlw-0061','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-62-1','古典的PNH','Classical Paroxysmal Nocturnal Hemoglobinuria',array['Classical Paroxysmal Nocturnal Hemoglobinuria']::text[],'mhlw-0062','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-62-2','骨髄不全型PNH','PNH in the setting of another specified bone marrow disorder',array['PNH in the setting of another specified bone marrow disorder']::text[],'mhlw-0062','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-62-3','混合型PNH','Paroxysmal nocturnal hemoglobinuria',array['Paroxysmal nocturnal hemoglobinuria']::text[],'mhlw-0062','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-64-1','先天性血栓性血小板減少性紫斑病','Congenital thrombotic thrombocytopenic purpura',array['Congenital thrombotic thrombocytopenic purpura']::text[],'mhlw-0064','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-64-2','後天性原発性血栓性血小板減少性紫斑病','Acquired idiopathic thrombotic thrombocytopenic purpura',array['Acquired idiopathic thrombotic thrombocytopenic purpura']::text[],'mhlw-0064','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-64-3','後天性二次性血栓性血小板減少性紫斑病','secondary thrombotic thrombocytopenic purpura',array['secondary thrombotic thrombocytopenic purpura']::text[],'mhlw-0064','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-1','X連鎖重症複合免疫不全症','X-linked severe combined immunodeficiency',array['X-linked severe combined immunodeficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-10','ウィスコット・オルドリッチ症候群','Wiskott-Aldrich syndrome',array['Wiskott-Aldrich症候群','Wiskott-Aldrich syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-11','毛細血管拡張性運動失調症','Ataxia telangiectasia',array['Ataxia telangiectasia']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-12','ナイミーヘン染色体不安定症候群','Nijmegen breakage syndrome',array['Nijmegen breakage症候群','Nijmegen breakage syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-13','ブルーム症候群','Bloom syndrome',array['Bloom症候群','Bloom syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-14','ICF症候群','ICF syndrome',array['ICF syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-15','PMS2異常症','PMS2 deficiency',array['PMS2 deficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-16','RIDDLE症候群','RIDDLE syndrome',array['RIDDLE syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-17','シムケ症候群','Schimke syndrome',array['Schimke症候群','Schimke syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-18','ネザートン症候群','Netherton syndrome',array['Netherton症候群','Netherton syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-19','胸腺低形成','thymus hypoplasia',array['22q11.2欠失症候群','DiGeorge症候群','thymus hypoplasia']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-2','細網異形成症','Reticular dysgenesis',array['Reticular dysgenesis']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-20','高IgE症候群','Hyper-IgE syndrome',array['Hyper-IgE syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-21','肝中心静脈閉鎖症を伴う免疫不全症','Hepatic veno-occlusive disease-immunodeficiency syndrome',array['Hepatic veno-occlusive disease-immunodeficiency syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-22','先天性角化不全症','Dyskeratosis congenita',array['Dyskeratosis congenita']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-23','X連鎖無ガンマグロブリン血症','X-linked agammaglobulinemia',array['X-linked agammaglobulinemia']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-25','高IgM症候群','Hyper IgM syndrome',array['Hyper IgM syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-26','IgGサブクラス欠損症','IgG subclass deficiency',array['IgG subclass deficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-27','選択的IgA欠損症','Selective IgA deficiency',array['Selective IgA deficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-28','特異抗体産生不全症','Specific antibody deficiency with normal Ig concentrations and normal numbers of B cells',array['Specific antibody deficiency with normal Ig concentrations and normal numbers of B cells']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-29','乳児一過性低ガンマグロブリン血症','Transient hypogammaglobulinaemia of infancy with normal numbers of B cells',array['Transient hypogammaglobulinaemia of infancy with normal numbers of B cells']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-3','アデノシンデアミナーゼ 欠損症','Adenosine deaminase deficiency',array['ADA欠損症','Adenosine deaminase deficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-30','チェディアック・東症候群','Chédiak-Higashi syndrome',array['Chédiak-Higashi症候群','Chédiak-Higashi syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-31','X連鎖リンパ増殖症候群','X-linked lymphoproliferative syndrome',array['X-linked lymphoproliferative syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-32','自己免疫性リンパ増殖症候群','Autoimmune lymphoproliferative syndrome',array['ALPS','Autoimmune lymphoproliferative syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-33','重症先天性好中球減少症','Severe congenital neutropenia',array['Severe congenital neutropenia']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-34','周期性好中球減少症','Cyclic neutropenia',array['Cyclic neutropenia']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-35','白血球接着不全症','Leukocyte adhesion deficiency',array['Leukocyte adhesion deficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-36','シュワッハマン・ダイアモンド症候群','Shwachman-Diamond syndrome',array['Shwachman-Diamond症候群','Shwachman-Diamond syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-37','慢性肉芽腫症','Chronic granulomatous disease',array['Chronic granulomatous disease']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-38','ミエロペルオキシダーゼ欠損症','Myeloperoxidase deficiency',array['Myeloperoxidase deficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-39','メンデル遺伝型マイコバクテリア易感染症','Mendelian susceptibility to mycobacterial disease',array['Mendelian susceptibility to mycobacterial disease']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-4','オーメン症候群','Omenn syndrome',array['Omenn症候群','Omenn syndrome']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-40','免疫不全を伴う無汗性外胚葉形成異常症','Anhidrotic ectodermal dysplasia with immunodeficiency',array['Anhidrotic ectodermal dysplasia with immunodeficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-41','IRAK4欠損症','IRAK4 deficiency',array['IRAK4 deficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-42','MyD88欠損症','MyD88 deficiency',array['MyD88 deficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-43','慢性皮膚粘膜カンジダ症','Chronic mucocutaneous candidiasis',array['Chronic mucocutaneous candidiasis']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-45','遺伝性血管性浮腫','Hereditary angioedema',array['C1インヒビター欠損症','Hereditary angioedema']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-5','プリンヌクレオシドホスホリラーゼ欠損症','Purine nucleoside phosphorylase deficiency',array['Purine nucleoside phosphorylase deficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-6','CD8欠損症','CD8 deficiency',array['CD8 deficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-7','ZAP-70欠損症','Zap-70 deficiency',array['Zap-70 deficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-8','MHCクラスI欠損症','MHC class I deficiency',array['MHC class I deficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-65-9','MHCクラスII欠損症','MHC class II deficiency',array['MHC class II deficiency']::text[],'mhlw-0065','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-67-1','常染色体優性多発性嚢胞腎','Autosomal Dominant Polycystic Kidney Disease',array['Autosomal Dominant Polycystic Kidney Disease']::text[],'mhlw-0067','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-67-2','常染色体劣性多発性嚢胞腎','Autosomal Recessive Polycystic Kidney Disease',array['Autosomal Recessive Polycystic Kidney Disease']::text[],'mhlw-0067','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-72-1','中枢性尿崩症','Central diabetes insipidus',array['バゾプレシン分泌低下症','Central diabetes insipidus']::text[],'mhlw-0072','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-76-1','中枢性思春期早発症','Central precocious puberty',array['中枢性性早熟症','Central precocious puberty']::text[],'mhlw-0076','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-76-2','特発性ゴナドトロピン分泌低下症','idiopathic hypogonadotropic hypogonadism',array['idiopathic hypogonadotropic hypogonadism']::text[],'mhlw-0076','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-76-3','家族性ゴナドトロピン分泌低下症','congenital hypogonadotropic hypogonadism',array['congenital hypogonadotropic hypogonadism']::text[],'mhlw-0076','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-76-4','続発性ゴナドトロピン分泌低下症','acquired hypogonadotropic hypogonadism',array['acquired hypogonadotropic hypogonadism']::text[],'mhlw-0076','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-76-5','下垂体ゴナドトロピン産生腫瘍','GH secreting pituitary adenoma',array['GH secreting pituitary adenoma']::text[],'mhlw-0076','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-78-2','副腎皮質刺激ホルモン分泌低下症','Syndrome of abnormal secretion of adrenocorticotropic hormone',array['ACTH分泌低下症','Syndrome of abnormal secretion of adrenocorticotropic hormone']::text[],'mhlw-0078','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-78-3','甲状腺刺激ホルモン分泌低下症','Syndrome of abnormal secretion of thyroid-stimulating hormone',array['TSH分泌低下症','Syndrome of abnormal secretion of thyroid-stimulating hormone']::text[],'mhlw-0078','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-78-4','GH 分泌不全性低身長症（小児）','Growth hormone secretion deficiency of dwarfism',array['成長ホルモン分泌不全症（小児）','Growth hormone secretion deficiency of dwarfism']::text[],'mhlw-0078','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-78-5','成人GH 分泌不全症','Adult growth hormone deficiency',array['成長ホルモン分泌不全症（成人）','Adult growth hormone deficiency']::text[],'mhlw-0078','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-78-6','プロラクチン分泌低下症','Syndrome of abnormal secretion of Prolactin',array['Syndrome of abnormal secretion of Prolactin']::text[],'mhlw-0078','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-81-1','先天性リポイド過形成症','Congenital Lipoid Adrenal Hyperplasia',array['Congenital Lipoid Adrenal Hyperplasia']::text[],'mhlw-0081','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-81-2','3β−水酸化ステロイド脱水素酵素欠損症','3β-Hydroxysteroid Dehydrogenase Deficiency',array['３β-HSD欠損症','3β-Hydroxysteroid Dehydrogenase Deficiency']::text[],'mhlw-0081','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-81-3','21-水酸化酵素欠損症','21-Hydroxylase deficiency',array['21-Hydroxylase deficiency']::text[],'mhlw-0081','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-81-4','11β-水酸化酵素欠損症','11β-Hydroxylase deficiency',array['11β-Hydroxylase deficiency']::text[],'mhlw-0081','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-81-5','17α−水酸化酵素欠損症','17α-Hydroxylase deficiency',array['17α-Hydroxylase deficiency']::text[],'mhlw-0081','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-81-6','P450オキシドレダクターゼ欠損症','P450 Oxidoreductase deficiency',array['POR欠損症','P450 Oxidoreductase deficiency']::text[],'mhlw-0081','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-82-1','DAX-1異常症','DAX1 abnormality',array['DAX1 abnormality']::text[],'mhlw-0082','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-82-2','SF-1異常症','SF-1 abnormality',array['SF-1/Ad4BP異常症','SF-1 abnormality']::text[],'mhlw-0082','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-82-3','IMAge症候群','IMAGe syndrome',array['IMAGe syndrome']::text[],'mhlw-0082','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-82-4','ACTH不応症','ACTH unresponsiveness',array['ACTH unresponsiveness']::text[],'mhlw-0082','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-82-4-1','MC2R異常症','MC2R deficiency',array['MC2R deficiency']::text[],'mhlw-0082','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-82-4-2','MRAP異常症','MRAP deficiency',array['MRAP deficiency']::text[],'mhlw-0082','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-82-5','Allgrove症候群','Allgrove Syndrome',array['TripleA症候群','Allgrove Syndrome']::text[],'mhlw-0082','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-83-1','アジソン病（自己免疫性副腎炎）','Autoimmune Addison disease',array['特発性アジソン病','Autoimmune Addison disease']::text[],'mhlw-0083','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-83-2','結核性アジソン病','Tuberculous Addison''s disease',array['Tuberculous Addison''s disease']::text[],'mhlw-0083','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-83-3','アジソン病（感染症）','Infectious Addison''s diseas',array['Infectious Addison''s diseas']::text[],'mhlw-0083','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-85-1','特発性肺線維症','Idiopathic pulmonary fibrosis',array['IPF','Idiopathic pulmonary fibrosis']::text[],'mhlw-0085','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-85-2','IPF以外の間質性肺炎',NULL,array[]::text[],'mhlw-0085','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-85-2-1','非特異的間質性肺炎','nonspecific interstitial pneumonia',array['NSIP','nonspecific interstitial pneumonia']::text[],'mhlw-0085','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-85-2-2','急性間質性肺炎','acute interstitial pneumonia',array['AIP','acute interstitial pneumonia']::text[],'mhlw-0085','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-85-2-3','特発性器質化肺炎','Cryptogenic organizing pneumonia',array['COP','Cryptogenic organizing pneumonia']::text[],'mhlw-0085','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-85-2-4','剥離型間質性肺炎','desquamative interstitial pneumonia',array['DIP','desquamative interstitial pneumonia']::text[],'mhlw-0085','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-85-2-5','呼吸細気管支炎関連間質性肺炎','Respiratory bronchiolitis-associated interstitial lung disease',array['RB-ILD','Respiratory bronchiolitis-associated interstitial lung disease']::text[],'mhlw-0085','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-85-2-6','リンパ球性間質性肺炎','Lymphoid interstitial pneumonia',array['LIP','Lymphoid interstitial pneumonia']::text[],'mhlw-0085','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-87-1','肺静脈閉塞症','Pulmonary Veno-Occlusive Disease',array['Pulmonary Veno-Occlusive Disease']::text[],'mhlw-0087','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-87-2','肺毛細血管腫症','Pulmonary Capillary Hemangiomatosis',array['Pulmonary Capillary Hemangiomatosis']::text[],'mhlw-0087','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-9-1','有棘赤血球舞踏病','Choreoacanthocytosis',array['Choreoacanthocytosis']::text[],'mhlw-0009','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-9-2','Mcleod症候群','McLeod syndrome',array['McLeod syndrome']::text[],'mhlw-0009','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-90-1','網膜色素変性症（孤発型）','Sporadic retinitis pigmentosa',array['Sporadic retinitis pigmentosa']::text[],'mhlw-0090','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-90-2','網膜色素変性症（常染色体優性遺伝子型）','autosomal dominant retinitis pigmentosa',array['autosomal dominant retinitis pigmentosa']::text[],'mhlw-0090','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-90-3','網膜色素変性症（常染色体劣性遺伝子型）','Autosomal Recessive Retinitis Pigmentosa',array['Autosomal Recessive Retinitis Pigmentosa']::text[],'mhlw-0090','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-90-4','網膜色素変性症（X染色体劣性遺伝子型）','X-linked recessive retinitis pigmentosa',array['X-linked recessive retinitis pigmentosa']::text[],'mhlw-0090','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-90-5','網膜色素変性症（二遺伝子異常型）','Digenic retinitis pigmentosa',array['Digenic retinitis pigmentosa']::text[],'mhlw-0090','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-95-1','自己免疫性肝炎（典型例）',NULL,array[]::text[],'mhlw-0095','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-95-2','自己免疫性肝炎（非典型例）',NULL,array[]::text[],'mhlw-0095','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-96-1','小腸型クローン病','Ileal Crohn''s disease',array['Ileal Crohn''s disease']::text[],'mhlw-0096','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-96-2','大腸型クローン病','Colonic Crohn Disease',array['Colonic Crohn Disease']::text[],'mhlw-0096','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-96-3','小腸大腸型クローン病','Crohn ileocolitis',array['Crohn ileocolitis']::text[],'mhlw-0096','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-96-4','特殊型クローン病','atypical crohn''s disease',array['atypical crohn''s disease']::text[],'mhlw-0096','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-97-1','潰瘍性大腸炎（全大腸炎型）','pan-ulcerative colitis',array['pan-ulcerative colitis']::text[],'mhlw-0097','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-97-2','潰瘍性大腸炎（左側大腸炎型）','left-sided colitis',array['left-sided colitis']::text[],'mhlw-0097','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-97-3','潰瘍性大腸炎（直腸炎型）','Ulcerative proctitis',array['Ulcerative proctitis']::text[],'mhlw-0097','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-97-4','潰瘍性大腸炎（右側型）','Right-sided ulcerative colitis',array['潰瘍性大腸炎（分節型）','Right-sided ulcerative colitis']::text[],'mhlw-0097','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-98-1','新生児乳児食物蛋白誘発胃腸炎','Neonatal food-protein induced enterocolitis',array['N-FPIES','Neonatal food-protein induced enterocolitis']::text[],'mhlw-0098','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-98-2','好酸球性食道炎','Eosinophilic esophagitis',array['EoE','Eosinophilic esophagitis']::text[],'mhlw-0098','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-98-3','好酸球性胃腸炎','Eosinophilic gastroenteritis',array['EGE','Eosinophilic gastroenteritis']::text[],'mhlw-0098','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json')
) as x(id,name_ja,name_en,aliases,parent_disease_id,source_url)
on conflict (id) do nothing;
