-- NANDO name imports. CC BY 4.0 NANDO/DBCLS.
-- Place after 012_nando_subtype_identity.sql and prior registry migrations.
insert into public.disease_catalog
 (id,name_ja,name_en,aliases,parent_disease_id,source_url,medical_review_status,published,concept_kind)
select x.id,x.name_ja,x.name_en,x.aliases,x.parent_disease_id,x.source_url,
 'name-only-unreviewed',true,'disease_subtype'
from (values
('nando-10-1','脱髄型CMT','Charcot-Marie-Tooth disease type 1',array['Charcot-Marie-Tooth disease type 1']::text[],'mhlw-0010','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-10-2','軸索型CMT','Charcot-Marie-Tooth disease type 2',array['Charcot-Marie-Tooth disease type 2']::text[],'mhlw-0010','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-10-3','中間型CMT','Intermediate Charcot-Marie-Tooth disease',array['Intermediate Charcot-Marie-Tooth disease']::text[],'mhlw-0010','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-106-1','家族性寒冷蕁麻疹','Familial cold autoinflammatorysyndrome',array['FCAS','Familial cold autoinflammatorysyndrome']::text[],'mhlw-0106','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-106-2','Muckle-Wells症候群','Muckle-Wells syndrome',array['MWS','Muckle-Wells syndrome']::text[],'mhlw-0106','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-106-3','CINCA症候群','Chronic infantile neurological cutaneous articular syndrome',array['NOMID','Chronic infantile neurological cutaneous articular syndrome']::text[],'mhlw-0106','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-107-1','全身型若年性特発性関節炎','Systemic juvenile idiopathic arthritis',array['Systemic juvenile idiopathic arthritis']::text[],'mhlw-0107','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-107-2','関節型若年性特発性関節炎','Articular-type juvenile idiopathic arthritis',array['Articular-type juvenile idiopathic arthritis']::text[],'mhlw-0107','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-109-1','先天性非典型溶血性尿毒症症候群','congenital atypical hemolytic uremic syndrome',array['congenital atypical hemolytic uremic syndrome']::text[],'mhlw-0109','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-109-2','後天性非典型溶血性尿毒症症候群','acquired aHUS',array['acquired aHUS']::text[],'mhlw-0109','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-111-1','ネマリンミオパチー','Nemaline myopathy',array['Nemaline myopathy']::text[],'mhlw-0111','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-111-2','セントラルコア病','Central core disease',array['Central core disease']::text[],'mhlw-0111','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-111-3','ミニコア病','Minicore myopathy',array['Minicore myopathy']::text[],'mhlw-0111','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-111-4','ミオチュブラーミオパチー','Myotubular myopathy',array['Myotubular myopathy']::text[],'mhlw-0111','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-111-5','中心核ミオパチー','Centronuclear myopathy',array['Centronuclear myopathy']::text[],'mhlw-0111','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-111-6','先天性筋線維タイプ不均等症','Congenital fiber-type disproportion myopathy',array['Congenital fiber-type disproportion myopathy']::text[],'mhlw-0111','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-111-7','全タイプ１繊維ミオパチー','Type 1 Fiber Predominance Myopathy',array['Type 1 Fiber Predominance Myopathy']::text[],'mhlw-0111','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-113-1','ジストロフィン異常症','Dystrophinopathies',array['Dystrophinopathies']::text[],'mhlw-0113','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-113-1-2','ベッカー型筋ジストロフィー','Becker muscular dystrophy',array['Becker muscular dystrophy']::text[],'mhlw-0113','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-113-2','肢帯型筋ジストロフィー','Limb-girdle muscular dystrophy',array['Limb-girdle muscular dystrophy']::text[],'mhlw-0113','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-113-3','顔面肩甲上腕型筋ジストロフィー','Facioscapulohumeral muscular dystrophy',array['Facioscapulohumeral muscular dystrophy']::text[],'mhlw-0113','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-113-4','エメリー・ドレイフス型筋ジストロフィー','Emery-Dreifuss muscular dystrophy',array['Emery-Dreifuss muscular dystrophy']::text[],'mhlw-0113','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-113-5','眼咽頭筋型筋ジストロフィー','Oculopharyngeal muscular dystrophy',array['Oculopharyngeal muscular dystrophy']::text[],'mhlw-0113','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-113-6','福山型先天性筋ジストロフィー','Fukuyama type congenital muscular dystrophy',array['Fukuyama type congenital muscular dystrophy']::text[],'mhlw-0113','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-113-7','筋強直性ジストロフィー','Myotonic dystrophy',array['Myotonic dystrophy']::text[],'mhlw-0113','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-114-1','先天性ミオトニー','Myotonia congenita',array['Myotonia congenita']::text[],'mhlw-0114','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-114-1-1','先天性ミオトニー（トムゼン病（優性遺伝））','Thomsen disease',array['トムゼン病','Thomsen disease']::text[],'mhlw-0114','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-114-1-2','先天性ミオトニー（ベッカー病（劣性遺伝））','Becker disease',array['ベッカー病','Becker disease']::text[],'mhlw-0114','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-114-2','ナトリウムチャネルミオトニー(カリウム惹起性ミオトニー)','Sodium channel myotonia',array['Sodium channel myotonia']::text[],'mhlw-0114','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-114-3','先天性パラミオトニー','Paramyotonia congenita',array['カリウム惹起性ミオトニー','Paramyotonia congenita']::text[],'mhlw-0114','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-115-1','遺伝性低カリウム性周期性四肢麻痺','Hereditary Hypokalemic Periodic Paralysis',array['Hereditary Hypokalemic Periodic Paralysis']::text[],'mhlw-0115','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-115-2','遺伝性高カリウム性周期性四肢麻痺','Hereditary Hyperkalemic Periodic Paralysis',array['正カリウム性周期性四肢麻痺','Hereditary Hyperkalemic Periodic Paralysis']::text[],'mhlw-0115','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-117-1','症候性脊髄空洞症','symptomatic Syringomyelia',array['symptomatic Syringomyelia']::text[],'mhlw-0117','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-117-2','無症候性脊髄空洞症','asymptomatic Syringomyelia',array['asymptomatic Syringomyelia']::text[],'mhlw-0117','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-1','DYT1ジストニア','DYT1 dystonia',array['DYT1 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-10','DYT10ジストニア','DYT10 dystonia',array['反復発作性運動誘発性ジスキネジア1','DYT10 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-11','DYT11ジストニア','DYT11 dystonia',array['ミオクローヌス・ジストニア症候群','DYT11 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-12','DYT12ジストニア','DYT12 dystonia',array['DYT12 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-12-1','急性発症ジストニア・パーキンソニズム','Rapid-onset dystonia-parkinsonism',array['Rapid-onset dystonia-parkinsonism']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-12-3','小脳失調症深部反射消失凹足視神経萎縮感覚神経障害性聴覚障害','cerebellar ataxia, areflexia, pes cavus, optic atropy, and sensorineural hearing loss',array['cerebellar ataxia, areflexia, pes cavus, optic atropy, and sensorineural hearing loss']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-13','DYT13ジストニア','DYT13 dystonia',array['DYT13 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-14','DYT15ジストニア','DYT15 dystonia',array['DYT15 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-15','DYT16ジストニア','DYT16 dystonia',array['DYT16 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-16','DYT17ジストニア','DYT17 dystonia',array['DYT17 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-17','DYT18ジストニア','DYT18 dystonia',array['発作性労作誘発性ジスキネジア','DYT18 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-18','DYT19ジストニア','DYT19 dystonia',array['反復発作性運動誘発性ジスキネジア2','DYT19 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-19','DYT20ジストニア','DYT20 dystonia',array['DYT20 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-2','DYT2ジストニア','DYT2 dystonia',array['DYT2 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-20','パントテン酸キナーゼ関連神経変性症（NBIA1）','NBIA１',array['NBIA1']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-20-1','パントテン酸キナーゼ変異に伴う神経変性症（古典型）','classical PKAN',array['classical PKAN']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-20-2','パントテン酸キナーゼ変異に伴う神経変性症（非典型例）','Atypical PKAN',array['Atypical PKAN']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-21','乳児神経軸索ジストロフィー（古典型）','NBIA2a',array['NBIA2a']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-22','乳児神経軸索ジストロフィー（非典型例）','NBIA2b',array['NBIA2b']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-23','神経フェリチン症','NBIA３',array['NBIA３']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-24','無セルロプラスミン血症','NBIA４',array['NBIA４']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-25','脂肪酸水酸化酵素変異に伴う神経変性症','FAHN',array['FAHN']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-3','DYT3ジストニア','DYT3 dystonia',array['X 染色体連鎖ジストニア・パーキンソニスム','DYT3 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-4','DYT4ジストニア','DYT4 dystonia',array['DYT4 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-5','DYT5ジストニア','DYT5 dystonia',array['DYT14ジストニア','瀬川病','ドパ反応性ジストニア','DYT5 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-6','DYT6ジストニア','DYT6 dystonia',array['DYT6 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-7','DYT7ジストニア','DYT7 dystonia',array['DYT7 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-8','DYT8ジストニア','DYT8 dystonia',array['発作性非運動誘発性ジスキネジア1','DYT8 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-120-9','DYT9ジストニア','DYT9 dystonia',array['発作性舞踏アテトーシス・痙性対麻痺','DYT9 dystonia']::text[],'mhlw-0120','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-127-1','（行動異常型）前頭側頭型認知症','Behavioral variant frontotemporal dementia',array['Behavioral variant frontotemporal dementia']::text[],'mhlw-0127','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-127-2','意味性認知症','Semantic dementia',array['Semantic dementia']::text[],'mhlw-0127','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-13-1-1','再発寛解型MS','Relapsing-remitting multiple sclerosis',array['Relapsing-remitting multiple sclerosis']::text[],'mhlw-0013','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-13-1-2','一次性進行型MS','primary progressive multiple sclerosis',array['primary progressive multiple sclerosis']::text[],'mhlw-0013','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-13-1-3','二次性進行型MS','secondary progressive multiple sclerosis',array['secondary progressive multiple sclerosis']::text[],'mhlw-0013','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-13-2','視神経脊髄炎','Neuromyelitis Optica',array['Neuromyelitis Optica']::text[],'mhlw-0013','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-13-3','Baló病','Baló concentric sclerosis',array['バロー同心円硬化症','Baló concentric sclerosis']::text[],'mhlw-0013','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-131-1','大脳優位型アレキサンダー病','Alexander disease type I',array['1型アレキサンダー病','Alexander disease type I']::text[],'mhlw-0131','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-131-2','延髄・脊髄優位型アレキサンダー病','Alexander disease type II',array['2型アレキサンダー病','Alexander disease type II']::text[],'mhlw-0131','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-131-3','中間型アレキサンダー病','Alexander disease type III',array['3型アレキサンダー病','Alexander disease type III']::text[],'mhlw-0131','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-134-1','中隔視神経形成異常症',NULL,array['ドモルシア症候群']::text[],'mhlw-0134','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-137-1','FCD タイプ1a','Focal cortical dysplasia type 1a',array['Focal cortical dysplasia type 1a']::text[],'mhlw-0137','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-137-2','FCD タイプ1b','Focal cortical dysplasia type 1b',array['Focal cortical dysplasia type 1b']::text[],'mhlw-0137','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-137-3','FCD タイプ1c','Focal cortical dysplasia type 1c',array['Focal cortical dysplasia type 1c']::text[],'mhlw-0137','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-137-4','FCD タイプ2a','Focal cortical dysplasia type 2a',array['Focal cortical dysplasia type 2a']::text[],'mhlw-0137','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-137-5','FCD タイプ2b','Focal cortical dysplasia type 2b',array['Focal cortical dysplasia type 2b']::text[],'mhlw-0137','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-137-6','FCD タイプ3a','Focal cortical dysplasia type 3a',array['Focal cortical dysplasia type 3a']::text[],'mhlw-0137','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-137-7','FCD タイプ3b','Focal cortical dysplasia type 3b',array['Focal cortical dysplasia type 3b']::text[],'mhlw-0137','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-137-8','FCD タイプ3c','Focal cortical dysplasia type 3c',array['Focal cortical dysplasia type 3c']::text[],'mhlw-0137','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-137-9','FCD タイプ3d','Focal cortical dysplasia type 3d',array['Focal cortical dysplasia type 3d']::text[],'mhlw-0137','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-139-1','ペリツェウス・メルツバッハ病','Pelizaeus-Merzbacher disease',array['Pelizaeus-Merzbacher disease']::text[],'mhlw-0139','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-139-10','失調、歯牙低形成を伴う髄鞘形成不全症','Ataxia, delayed dentition, and hypomyelination',array['Ataxia, delayed dentition, and hypomyelination']::text[],'mhlw-0139','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-139-11','脱髄型末梢神経障害、中枢性髄鞘形成不全症、ワーデンバーグ症候群、ヒルシュスプルング病','Peripheral demyelinating neuropathy, central dysmyelinating leukodystrophy, Waardenburg syndrome, and Hirschsprung disease',array['Peripheral demyelinating neuropathy, central dysmyelinating leukodystrophy, Waardenburg syndrome, and Hirschsprung disease']::text[],'mhlw-0139','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-139-2','ペリツェウス・メルツバッハ様病１','Pelizaeus-Merzbacher like disease',array['Pelizaeus-Merzbacher like disease']::text[],'mhlw-0139','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-139-3','基底核および小脳萎縮を伴う髄鞘形成不全症','Hypomyelination with atrophy of the basal ganglia and cerebellum',array['Hypomyelination with atrophy of the basal ganglia and cerebellum']::text[],'mhlw-0139','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-139-4','18q欠失症候群','18q-syndrome',array['18q-syndrome']::text[],'mhlw-0139','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-139-5','アラン・ハーンドン・タドリー症候群','Allan-Herndon-Dudley syndrome',array['Allan-Herndon-Dudley syndrome']::text[],'mhlw-0139','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-139-6','HSP60 chaperon病','Mitochondrial Hsp60 chaperonopathy',array['Mitochondrial Hsp60 chaperonopathy']::text[],'mhlw-0139','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-139-8','小脳萎縮と脳梁低形成を伴うび漫性大脳白質形成不全症','Diffuse cerebral hypomyelination with cerebellar atrophy and hypoplasia of the corpus callosum',array['Diffuse cerebral hypomyelination with cerebellar atrophy and hypoplasia of the corpus callosum']::text[],'mhlw-0139','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-139-9','先天性白内障を伴う髄鞘形成不全症','Hypomyelination and congenital cataract',array['Hypomyelination and congenital cataract']::text[],'mhlw-0139','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-14-2','多巣性運動ニューロパチー','Multifocal motor neuropathy',array['Multifocal motor neuropathy']::text[],'mhlw-0014','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-156-1','典型的レット症候群',NULL,array[]::text[],'mhlw-0156','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-156-2','非典型的レット症候群','Atypical Rett syndrome',array['Atypical Rett syndrome']::text[],'mhlw-0156','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-1','ケラチン症性魚鱗癬','Keratinopathic ichthyosis',array['Keratinopathic ichthyosis']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-1-1','常染色体優性表皮融解性魚鱗癬','Autosomal dominant epidermolytic ichthyosis',array['Autosomal dominant epidermolytic ichthyosis']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-1-2','常染色体劣性表皮融解性魚鱗癬','Autosomal recessive epidermolytic ichthyosis',array['Autosomal recessive epidermolytic ichthyosis']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-1-3','表在性表皮融解性魚鱗癬','Superficial epidermolytic ichthyosis',array['Superficial epidermolytic ichthyosis']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-2','道化師様魚鱗癬','Harlequin ichthyosis',array['Harlequin ichthyosis']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-3','道化師様魚鱗癬以外の常染色体劣性遺伝性魚鱗癬','Autosomal recessive congenital ichthyosis',array['Autosomal recessive congenital ichthyosis']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-3-1','先天性魚鱗癬様紅皮症','Congenital Ichthyosiform Erythroderma',array['Congenital Ichthyosiform Erythroderma']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-3-2','葉状魚鱗癬','Lamellar ichthyosis',array['Lamellar ichthyosis']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-4','魚鱗癬症候群','Ichthyosis syndrome',array['Ichthyosis syndrome']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-4-10','毛包性魚鱗癬','Ichthyosis Follicularis',array['Ichthyosis Follicularis']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-4-11','CHILD症候群','congenital hemidysplasia, ichthyosiform erythroderma or nevus, and limb defects syndrome',array['congenital hemidysplasia, ichthyosiform erythroderma or nevus, and limb defects syndrome']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-4-12','Conradi-Hünermann-Happle 症候群','Conradi Hünermann Happle syndrome',array['Conradi Hünermann Happle syndrome']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-4-2','シェーグレン・ラルソン症候群','Sjögren-Larsson syndrome',array['Sjögren-Larsson syndrome']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-4-3','KID症候群','Keratitis-ichthyosis-deafness syndrome',array['Keratitis-ichthyosis-deafness syndrome']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-4-4','ドルフマン・シャナリン症候群','Dorfman-Chanarin syndrome',array['Dorfman-Chanarin syndrome']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-4-5','中性脂肪蓄積症','Neutral lipid storage disease with ichthyosis',array['Neutral lipid storage disease with ichthyosis']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-4-6','多発性スルファターゼ欠損症','Multiple sulfatase deficiency',array['Multiple sulfatase deficiency']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-4-7','X連鎖性劣性魚鱗癬症候群','Recessive X-linked ichtyosis',array['Recessive X-linked ichtyosis']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-4-8','IBID症候群（魚鱗癬・脆毛などを伴う疾患）','ichthyosis, brittle hair, impaired intelligence, decreased fertility and short stature',array['IBID','ichthyosis, brittle hair, impaired intelligence, decreased fertility and short stature']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-160-4-9','硫黄欠乏性毛髪発育異常症','Trichothiodystrophy',array['Trichothiodystrophy']::text[],'mhlw-0160','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-162-1','水疱性類天疱瘡','bullous pemphigoid',array['bullous pemphigoid']::text[],'mhlw-0162','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-162-2','粘膜類天疱瘡','mucous membrane pemphigoid',array['mucous membrane pemphigoid']::text[],'mhlw-0162','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-162-3','後天性表皮水疱症','Epidermolysis bullosa acquisita',array['Epidermolysis bullosa acquisita']::text[],'mhlw-0162','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-164-1','ヘルマンスキー・パドラック症候群','Hermansky-Pudlak syndrome',array['Hermansky-Pudlak syndrome']::text[],'mhlw-0164','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-164-3','グリセリ症候群','Griscelli syndrome',array['Griscelli syndrome']::text[],'mhlw-0164','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-164-4','非症候型の眼皮膚白皮症','non-syndromic oculocutaneous albinism',array['非症候性眼皮膚白皮症','non-syndromic oculocutaneous albinism']::text[],'mhlw-0164','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-168-1','古典型エーラス・ダンロス症候群','Ehlers-Danlos syndrome, classic type',array['Ehlers-Danlos syndrome, classic type']::text[],'mhlw-0168','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-168-2','関節型エーラス・ダンロス症候群','Ehlers-Danlos syndrome, hypermobility type',array['Ehlers-Danlos syndrome, hypermobility type']::text[],'mhlw-0168','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-168-3','血管型エーラス・ダンロス症候群','Ehlers-Danlos syndrome, vascular type',array['Ehlers-Danlos syndrome, vascular type']::text[],'mhlw-0168','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-168-4','後側彎型エーラス・ダンロス症候群','Ehlers-Danlos syndrome, kyphoscoliotic type',array['Ehlers-Danlos syndrome, kyphoscoliotic type']::text[],'mhlw-0168','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-168-5','多発関節弛緩型エーラス・ダンロス症候群','Ehlers-Danlos syndrome, arthrochalasis type',array['Ehlers-Danlos syndrome, arthrochalasis type']::text[],'mhlw-0168','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-168-6','皮膚脆弱型エーラス・ダンロス症候群','Ehlers-Danlos syndrome, dermatosparaxis type',array['Ehlers-Danlos syndrome, dermatosparaxis type']::text[],'mhlw-0168','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-168-7','デルマタン4-O-硫酸基転移酵素-1欠損型エーラス・ダンロス症候群','Dermatan 4-O-sulfotransferase 1 Deficient Ehlers-Danlos Syndrome',array['Dermatan 4-O-sulfotransferase 1 Deficient Ehlers-Danlos Syndrome']::text[],'mhlw-0168','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-17-1','多系統萎縮症（小脳型・MSA-C）','Multiple system atrophy, cerebellar type',array['MSA-C','Multiple system atrophy, cerebellar type']::text[],'mhlw-0017','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-17-2','多系統萎縮症（パーキンソン型・MSA-P）','Multiple system atrophy, parkinsonian type',array['MSA-P','Multiple system atrophy, parkinsonian type']::text[],'mhlw-0017','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-177-1','有馬症候群','Arima syndrome',array['Arima syndrome']::text[],'mhlw-0177','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-1','孤発性脊髄小脳変性症','Sporadic Spinocerebellar Degeneration',array['Sporadic Spinocerebellar Degeneration']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-1-1','皮質性小脳萎縮症','cortical cerebellar atrophy',array['cortical cerebellar atrophy']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-2','常染色体優性遺伝性脊髄小脳変性症','autosomal dominant spinocerebellar degeneration',array['autosomal dominant spinocerebellar degeneration']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-2-1','脊髄小脳失調症３型','spinocerebellar ataxia type 3',array['spinocerebellar ataxia type 3']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-2-2','脊髄小脳失調症６型','spinocerebellar ataxia type 6',array['spinocerebellar ataxia type 6']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-2-3','歯状核赤核淡蒼球ルイ体萎縮症','Dentatorubropallidoluysian atrophy',array['Dentatorubropallidoluysian atrophy']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-2-4','脊髄小脳失調症３１型','spinocerebellar ataxia type 31',array['spinocerebellar ataxia type 31']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-2-5','脊髄小脳失調症１型','spinocerebellar ataxia type 1',array['spinocerebellar ataxia type 1']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-2-6','脊髄小脳失調症２型','spinocerebellar ataxia type 2',array['spinocerebellar ataxia type 2']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-2-7','脊髄小脳失調症７型','spinocerebellar ataxia type 7',array['spinocerebellar ataxia type 7']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-2-8','脊髄小脳失調症３６型','spinocerebellar ataxia type 36',array['spinocerebellar ataxia type 36']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-3','常染色体劣性遺伝性脊髄小脳変性症','autosomal recessive spinocerebellar degeneration',array[]::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-3-1','ビタミンE単独欠乏性失調症','Ataxia with isolated vitamin E deficiency',array['Ataxia with isolated vitamin E deficiency']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-3-2','アプラタキシン欠損症','ataxia-oculomotor apraxia Type 1',array['眼球運動失行・低アルブミン血症を伴う早発型失調症','ataxia-oculomotor apraxia Type 1']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-4','痙性対麻痺','hereditary spastic paraplegia',array['hereditary spastic paraplegia']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-4-1','痙性対麻痺（純粋型）','pure hereditary spastic paraplegia',array['pure hereditary spastic paraplegia']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-18-4-2','痙性対麻痺（複合型）','complex hereditary spastic paraplegia',array['complex hereditary spastic paraplegia']::text[],'mhlw-0018','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-1-1','Gaucher病１型','Gaucher disease type 1',array['Gaucher disease type 1']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-1-2','Gaucher病２型','Gaucher disease type 2',array['Gaucher disease type 2']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-1-3','Gaucher病３型','Gaucher disease type 3',array['Gaucher disease type 3']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-10','Hurler症候群','Hurler syndrome',array['ムコ多糖症I型','Hurler syndrome']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-11','Scheie症候群','Scheie syndrome',array['ムコ多糖症I型','Scheie syndrome']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-12','Hurler／Scheie症候群','Hurler-Scheie syndrome',array['ムコ多糖症I型','Hurler-Scheie syndrome']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-13','Hunter症候群','Hunter syndrome',array['Hunter syndrome']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-13-1','Hunter症候群（重症型）','Hunter syndrome type A',array['ムコ多糖症II型','Hunter syndrome type A']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-13-2','Hunter症候群（軽症型）','Hunter syndrome type B',array['ムコ多糖症II型','Hunter syndrome type B']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-14','Sanfilippo症候群','Sanfilippo syndrome',array['Sanfilippo syndrome']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-14-1','Sanfilippo症候群A型','Sanfilippo syndrome type A',array['ムコ多糖症III型','Sanfilippo syndrome type A']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-14-2','Sanfilippo症候群B型','Sanfilippo syndrome type B',array['ムコ多糖症III型','Sanfilippo syndrome type B']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-14-3','Sanfilippo症候群C型','Sanfilippo syndrome type C',array['ムコ多糖症III型','Sanfilippo syndrome type C']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-14-4','Sanfilippo症候群D型','Sanfilippo syndrome type D',array['ムコ多糖症III型','Sanfilippo syndrome type D']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-15','Morquio症候群','Morquio disease',array['Morquio disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-15-1','Morquio症候群A型','Morquio disease type A',array['ムコ多糖症IV型','Morquio disease type A']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-15-2','Morquio症候群B型','Morquio disease type B',array['ムコ多糖症IV型','Morquio disease type B']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-16','Maroteaux-Lamy症候群','Maroteaux-Lamy syndrome',array['Maroteaux-Lamy syndrome']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-16-1','Maroteaux-Lamy症候群（重症型）','Mucopolysaccharidosis type 6, rapidly progressing',array['ムコ多糖症VI型','Mucopolysaccharidosis type 6, rapidly progressing']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-16-2','Maroteaux-Lamy症候群（軽症型）','Mucopolysaccharidosis type 6, slowly progressing',array['ムコ多糖症VI型','Mucopolysaccharidosis type 6, slowly progressing']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-17','Sly病','Sly syndrome',array['Sly syndrome']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-17-1','Sly病（新生児型）',NULL,array['ムコ多糖症VII型']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-17-2','Sly病（中間型）',NULL,array['ムコ多糖症VII型']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-17-3','Sly病（軽症型）',NULL,array['ムコ多糖症VII型']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-18','ヒアルロニダーゼ欠損症','Hyaluronidase deficiency',array['ムコ多糖症IX型','Hyaluronidase deficiency']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-19','シアリドーシス','Sialidosis',array['Sialidosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-19-1','シアリドーシス（Ⅰ型）','Sialidosis type 1',array['Sialidosis type 1']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-19-2','シアリドーシス（Ⅱ型）','Sialidosis type 2',array['Sialidosis type 2']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-2','Niemann-Pick病A、B型','Niemann-Pick disease Type A, B',array['Niemann-Pick disease Type A, B']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-2-1','Niemann-Pick病A型','Niemann-Pick disease type A',array['Niemann-Pick disease type A']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-2-2','Niemann-Pick病B型','Niemann-Pick disease type B',array['Niemann-Pick disease type B']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-20','ガラクトシアリドーシス','Galactosialidosis',array['Galactosialidosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-20-1','ガラクトシアリドーシス（新生児及び早期乳児型）','Early-infantile galactosialidosis',array['Early-infantile galactosialidosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-20-2','ガラクトシアリドーシス（晩期乳児型）','Late infantile galactosialidosis',array['Late infantile galactosialidosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-20-3','ガラクトシアリドーシス（若年及び成人型）','Juvenile/adult galactosialidosis',array['Juvenile/adult galactosialidosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-21','ムコリピドーシスII型,III型','Mucolipidosis Type II,III',array['Mucolipidosis Type II,III']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-21-1','ムコリピドーシスII型','Mucolipidosis Type II',array['Mucolipidosis Type II']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-21-2','ムコリピドーシスIII型','Mucolipidosis Type III',array['Mucolipidosis Type III']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-22','α-マンノシドーシス','Alpha-mannosidosis',array['Alpha-mannosidosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-22-1','α-マンノシドーシス（乳児型）','Alpha-mannosidosis, infantile form',array['Alpha-mannosidosis, infantile form']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-22-2','α-マンノシドーシス（若年成人型）','Alpha-mannosidosis, adult form',array['Alpha-mannosidosis, adult form']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-23','β-マンノシドーシス','Beta-mannosidosis',array['Beta-mannosidosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-24','フコシドーシス','Fucosidosis',array['Fucosidosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-24-1','フコシドーシス（乳児型）','Fucosidosis type 1',array['Fucosidosis type 1']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-24-2','フコシドーシス（軽症型）','Fucosidosis type 2',array['Fucosidosis type 2']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-25','アスパルチルグルコサミン尿症','Aspartylglucosaminuria',array['Aspartylglucosaminuria']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-26','Schindler病','Schindler disease',array['Schindler disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-26-1','Schindler病I型','Schindler disease type 1',array['Schindler disease type 1']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-26-2','Schindler病II型','Schindler disease type 2',array['神崎病','Schindler disease type 2']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-26-3','Schindler病III型','Schindler disease type 3',array['Schindler disease type 3']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-27-1','Pompe病（乳児型）','Classic infantile-onset Pompe disease',array['Classic infantile-onset Pompe disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-27-2','Pompe病（小児型）','Non-classic infantile-onset Pompe disease',array['Non-classic infantile-onset Pompe disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-27-3','Pompe病（成人型）','Late-onset Pompe disease',array['Late-onset Pompe disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-28','酸性リパーゼ欠損症','Lysosomal acid lipase deficiency',array['Lysosomal acid lipase deficiency']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-28-1','ウォルマン病','Wolman disease',array['Wolman disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-28-2','コレステロールエステル蓄膿症','Cholesterol ester storage disease',array['Cholesterol ester storage disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-29','Danon病','Danon disease',array['Danon disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-3','Niemann-Pick病C型','Niemann-Pick disease Type C',array['Niemann-Pick disease Type C']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-3-1','Niemann-Pick病C型（乳児型）',NULL,array[]::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-3-2','Niemann-Pick病C型（成人型）',NULL,array[]::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-30','遊離シアル酸蓄積症','Free sialic acid storage disease',array['Free sialic acid storage disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-30-1','遊離シアル酸蓄積症（乳児型）','Free sialic acid storage disease, infantile form',array['遊離シアル酸蓄積症（重症型）','Free sialic acid storage disease, infantile form']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-30-2','遊離シアル酸蓄積症（中間型）','intermediate severe Salla disease',array['intermediate severe Salla disease']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-30-3','サラ病','Salla disaese',array['遊離シアル酸蓄積症（軽症型）','Salla disaese']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-31','セロイドリポフスチノーシス','Neuronal Ceroid Lipofuscinosis',array['Neuronal Ceroid Lipofuscinosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-31-1','セロイドリポフスチノーシス（先天型）','Congenital neuronal ceroid lipofuscinosis',array['Congenital neuronal ceroid lipofuscinosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-31-2','セロイドリポフスチノーシス（乳児型）','Infantile neuronal ceroid lipofuscinosis',array['Infantile neuronal ceroid lipofuscinosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-31-3','セロイドリポフスチノーシス（遅発乳児型）','Late infantile neuronal ceroid lipofuscinosis',array['Late infantile neuronal ceroid lipofuscinosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-31-4','セロイドリポフスチノーシス（若年型）','Juvenile neuronal ceroid lipofuscinosis',array['Juvenile neuronal ceroid lipofuscinosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-31-5','セロイドリポフスチノーシス（成人型）','Adult neuronal ceroid lipofuscinosis',array['Adult neuronal ceroid lipofuscinosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json'),
('nando-19-31-6','セロイドリポフスチノーシス（非定型型）','Atypical neuronal ceroid-lipofuscinosis',array['Atypical neuronal ceroid-lipofuscinosis']::text[],'mhlw-0019','https://github.com/NanbyoData/nando/blob/master/data/nanbyo.json')
) as x(id,name_ja,name_en,aliases,parent_disease_id,source_url)
on conflict (id) do nothing;
